### ISSUE TITLE
More concise recipes

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#113]
* If I want to switch branches, I have to specify the other keys in the recipe.
* If I want to specify a fork, I have to specify the whole recipe *and* add my fork, which is probably on the same host and with the same name.

Sub-issues:

* https://github.com/raxod502/straight.el/issues/93
* https://github.com/raxod502/straight.el/issues/114
* https://github.com/raxod502/straight.el/issues/116

**Comment by vyp** [comment]
:+1: Yeah I was wondering if there was a way to modify only particular attributes of a recipe? (and inherit anything missing from recipe repositories?)

**Comment by raxod502** [comment]
Not at the moment. Either inheritance will be enabled by default (most likely option), or you can opt-in with `:inherit t`. That will most likely be customizable. See also #114.

**Comment by vyp** [comment]
Maybe it should be opt-in by default in case the original recipes change? Related question, are recipe repositories locked in the lockfile as well? (which I would have known the answer to if I've used straight.el yet, sorry) Because if not, what if say a project changes it's file structure, and changes it's :files in it's recipe too, but your locked in version is before they changed their file structure, so the recipe wouldn't work.

**Comment by raxod502** [comment]
Recipe repositories are saved in the lockfile, since https://github.com/raxod502/straight.el/commit/f1f7007966bbbd6f06d36ed497d848958d42973a. There's therefore no concern about the underlying recipes changing. I wouldn't claim `straight.el` provided reproducibility if such a thing were possible.

**Comment by vyp** [comment]
Awesome. :sparkles: In that case default or not it should be fine.

**Comment by raxod502** [comment]
Note that dealing with such an update still requires care, since you must update both the recipe repository and the package simultaneously in that case. This is a general problem with packages that depend on one another as well, since `straight.el` makes no effort to provide dependency resolution beyond a list of package names that are required (on the basis that nobody provides good enough information for dependencies between arbitrary Git revisions of packages).

**Comment by vyp** [comment]
Yeah I understand, that's fine because there's nothing you can do about that.

> straight.el makes no effort to provide dependency resolution beyond a list of package names that are required

What do you mean by dependency resolution?

**Comment by raxod502** [comment]
* https://stackoverflow.com/q/28099683/3538165
* https://docs.npmjs.com/how-npm-works/npm3
* anything else that makes you think about dependency hell

The `straight.el` approach is to assume that since you use Emacs and find it compelling to use a package manager that can only be configured by writing code in your init-file, you're used to things breaking and requiring some manual patches every once in a while. Thus advanced concepts such as *versions*, *conflicts*, *compatibility*, *version ranges*, and so on are simply not applicable 😄 (I have enough conceptual trouble figuring out how to wrangle a declarative environment out of the mutable mess that is Emacs and Git, no need to complicate things further!).

**Comment by vyp** [comment]
Ah right, yeah there's just not enough dependency version information out there to even attempt this IMO, so fully agree.

And being able to lock in an already working environment into the lockfile sort of reduces the need for that stuff as well. i.e. It should work when reproducing/reinstalling, but you could still run into issues when updating. And if you do, you could just rollback your lockfile if you've put it under vc and wait for packages to be fixed or whatever before trying again. But practically speaking, you rarely run into dependency version resolution issues when using emacs packages anyway.
 
(Also the npm article though is just about directory structure really, but they're calling it dependency resolution :woman_shrugging: ...which is why I asked what you meant. :/ )

**Comment by progfolio** [comment]
> If I want to specify a fork, I have to specify the whole recipe and add my fork, which is probably on the same host and with the same name.

Here's a sketch of how I think this could be implemented:

Introduce a variable to store host, username associations:

    (defcustom straight-host-usernames nil
      "Alist mapping forge :host types to usernames.")
    
    ;;e.g.
    (setq straight-host-usernames '((gitlab . "my-gitlab-username")
                                    (github . "my-github-username")))

If `:fork` is a string without a slash, consider it to be the username portion of the `:repo`.
Inherit the repo name and host.

    (package :fork "user")

Becomes:

    (package :fork "user/inherited-repo-name")

If `:fork` is a string prefixed with a slash, check for host association in `straight-host-usernames`
Error if no association, otherwise compute repo name based off that.

    (package :fork "/forked-repo-name")

Becomes:

    ;; :host inherited from recipe
    (package :fork "my-github-username/forked-repo-name")

One could also override the `:host` within the `:fork` plist:

    (package :fork (:repo "/forked-repo-name" :host gitlab))

Becomes:

    (package :fork "my-gitlab-username/forked-repo-name")

If `:fork` is `t` inherit the `:host` and repo portion of `:repo` string. Compute username from `straight-host-usernames`:

    (package :fork t)

Becomes:

    (package :fork "my-github-username/inherited-repo-name")

Ideally one could still override the `:host` in the fork plist:

    (package :fork (:host gitlab))

Becomes:

    (package :fork "my-gitlab-username/inherited-repo-name")

If you think this behavior sounds reasonable, I should have some time to look into implementing it.

**Comment by raxod502** [comment]
That behavior all sounds great! Thank you for taking the time to outline it.

**Comment by progfolio** [comment]
Great! I'll take a swing at an implementation.

**Comment by raxod502** [comment]
Well, I think we have successfully closed out all parts of this long-standing issue, thanks most recently to the great contributions by @progfolio. Onwards and upwards!
