### ISSUE TITLE
Can this be installed from MELPA?

### ISSUE THREAD

**Issue by eflanigan00** [raxod502/straight.el#134]
I see the bootstrap code but haven't read through it yet to see how it works.
I think your package will get a lot more visibility if it is on MELPA. Just a thought.

I was not aware of it until I saw the post in this thread:
[Autoloads for local packages](https://emacs.stackexchange.com/questions/33627/how-to-generate-and-activate-autoloads-for-local-packages)

Thanks for the great package, I'm looking forward to trying it out.

**Comment by raxod502** [comment]
Good to know my shameless self-promotion is paying off ;)

Unfortunately it doesn't really make sense to install `straight.el` from MELPA, for a couple of reasons:

1. Doing so would require the installation to be done using a different package manager, which wouldn't have advanced support for things like making sure to install the correct version of `straight.el` and allowing you to specify a custom recipe for it.
2. If you installed `straight.el` via another package manager, such as `package.el`, then `straight.el` wouldn't be able to manage its own installation. (And in the case of `package.el`, you wouldn't even get the source code, only the built package.)
3. `straight.el` operates solely by observing what you do in your init-file, and making the rest of your package management conform to that specification. Thus there is no concept of "installing" `straight.el`: since it's a *functional* package manager, the "installation" is putting the configuration code in your init-file, and the "uninstallation" is taking the configuration code back out of your init-file (as contrasted with `package.el`, which has all kinds of mutable state stored outside the init-file).

That said something I have considered is putting a dummy package called `straight` on MELPA, which would just launch an interactive tutorial on how to install `straight.el` the proper way. I think this might make it easier for people to get started.

**Comment by eflanigan00** [comment]
Thanks, I like the dummy package and video idea.

**Comment by raxod502** [comment]
@eflanigan00 I've created https://github.com/melpa/melpa/issues/4939; you may want to follow that thread.

**Comment by raxod502** [comment]
Well, that's that. It appears that it will never be possible to install `straight.el` from MELPA.

I'll be happy to reopen this issue if somebody has an idea about how to install `straight.el` via `package.el` without losing any of the features. But I strongly doubt that this will be possible, because `package.el` sucks.
