### ISSUE TITLE
Integrate with use-package without overriding :ensure?

### ISSUE THREAD

**Issue by blaenk** [raxod502/straight.el#135]
I was looking at some options for augmenting my use of package.el + MELPA. In particular I was interested in using a dev branch of a particular MELPA package. I found this one and it seemed very nice, but perhaps I misunderstood its intended use case.

I was hoping to be able to use its use-package integration such that I could continue to use it the way I do now (it uses MELPA and assumes `:ensure t` to pull from MELPA), _but_ have an opt-in for making particular packages use straight.el, presumably implied by the mere existence of the `:recipe` handler. Perhaps this could be achieved through the addition of a setting to specify that the `:ensure t` shouldn't be automatically handled by straight.el unless `:recipe` is present? Or is what I'm trying to do a non-goal? If so, could you recommend any other package that may accomplish this?

I noticed the readme says this:

> By default, straight.el overrides use-package so that :ensure installs packages using straight.el instead of package.el. (You can override this behavior by customizing straight-enable-use-package-integration.)

I thought that might mean that I could set `straight-enable-use-package-integration` to `nil` to only disable overriding `:ensure` but still inserting the `:recipe` handler, but I seached `straight.el` and found no mention of that variable besides its `defcustom`.

**Comment by blaenk** [comment]
I'm wondering if, failing that, I could disable use-package integration and then manually call `(straight-use-package 'my-package)`, then I can use `(use-package my-package :ensure nil ...)` to still use use-package's features without making it install things? I believe that should work, I'm just wondering if mixing these two, i.e. using package.el + MELPA by default but straight.el for certain packages, will lead to any problems.

**Comment by blaenk** [comment]
I just noticed that Quelpa's use-package integration [seems to support this use case](https://github.com/quelpa/quelpa-use-package#overriding-use-package-always-ensure), in case it isn't the case that this is a non-goal, and you may gain some insight from it.

**Comment by vyp** [comment]
See https://github.com/raxod502/straight.el/issues/128#issuecomment-321956872 for this.

And also, setting `straight-enable-use-package-integration` to `nil` not working was a bug now fixed in develop: https://github.com/raxod502/straight.el/issues/128#issuecomment-322512782

**Comment by raxod502** [comment]
Thanks @vyp.

@blaenk The only thing I have to say is that `straight.el` is 100% compatible with MELPA, so you're not losing anything if you just switch over entirely.

By the way, `quelpa-use-package` is actually a complete hack. It doesn't use the official extension API exposed by `use-package`, and it also doesn't use the official `:ensure` extension API provided by `use-package` (the latter is quite understandable since the API didn't exist when `quelpa-use-package` was first written).

If you want more convenient syntax for this, you're going to have to report it upstream: the fundamental problem is that `use-package` doesn't support using different package managers for the `:ensure` keywords of different `use-package` forms, and working around that in `straight.el` would be an ugly hack. (Although if somebody provided a pull request that made it work without breaking existing usage, I would consider merging it.)

**Comment by blaenk** [comment]
Thanks @vyp that comment answers my question perfectly.

I would be open to using straight.el entirely. My main concern is that while linux is my primary dev platform, I also do use my setup on windows sometimes and I've found git to be painfully slow on it, like you couldn't imagine. Just bringing up a magit-status buffer takes a few seconds, let alone the dozens of packages I use. It seems to be a [well known issue](https://emacs.stackexchange.com/questions/19440/magit-extremely-slow-in-windows-how-do-i-optimize). Since I'm _otherwise_ perfectly comfortable using package.el/MELPA I figured I'd use straight.el for the one or two package forks/dev branches I needed to run. I guess I'll try what you suggested in the linked comment, what I was thinking I may do in the worst case:

``` elisp
(straight-use-package 'el-patch)
(use-package el-patch
  :ensure nil
  <whatever>)
```

Thanks on letting me know about how quelpa-use-package is implemented. I figured it might use use-package's API. I also wasn't aware of that limitation on `use-package`'s end. I was under the impression that it might be possible to "simply" set `:ensure nil` to opt-out of my default use of it (I have it default to `t` to use MELPA/package.el) and then the presence and handler of `:recipe` would note that `:ensure` was `nil`, as a go-ahead to use straight.el instead. I realize though that that would be overloading expected behavior so it's probably not desirable.

**Comment by raxod502** [comment]
Good point on Windows: it's not yet supported, see https://github.com/raxod502/straight.el/issues/124.

What I would recommend doing is only loading `straight.el` on non-Windows operating systems, and otherwise loading `package.el`. Then, you're using a single package manager in any given instance of your Emacs configuration, but you don't have to worry about making `use-package` delegate to different package managers conditionally.

Regarding the performance, I will point out that it shouldn't be an issue during startup (Git is not invoked at all), but only when installing packages initially and when updating/otherwise managing them. But of course that's a moot point at the moment since `straight.el` doesn't yet work on Windows at all.

**Comment by blaenk** [comment]
Ah that's good to know. I'll have to think about that then, thanks for all of the information!

**Comment by raxod502** [comment]
This issue is now completely resolved since `straight.el` uses a different keyword (`:straight`) and does not modify `:ensure` in any way.
