### ISSUE TITLE
Some GNU elpa packages are unavailable

### ISSUE THREAD

**Issue by dieggsy** [raxod502/straight.el#151]
I know GNU elpa support was dropped in favor of Melpa and/or emacsmirror recently, but sometimes I want a package that shows up in `M-x package-install` but not in `straight-use-package` , e.g. `dired-du`. I'm not sure if this is expected or what I could do about this.

**Comment by dieggsy** [comment]
Huh, this is odd as `dired-du` is available through emacsmirror

**Comment by jacktasia** [comment]
@dieggsy  I am not the maintainer of this project, but FWIW when using `(straight-use-package 'use-package)` this:

```
(use-package dired-du
  :ensure t
  :recipe (:host github :repo "emacsmirror/dired-du"))
```

works for me. Although not sure if this is the best way.

**Comment by raxod502** [comment]
This is probably another old package that was removed by @tarsius from the EmacsMirror before he stopped removing old packages, similarly to https://github.com/emacsmirror/epkgs/issues/1.

@jacktasia I think that is the best way. If you want it from GNU ELPA, you can always get it from there as well, using the following recipe:

```
(dired-du :type git :repo "https://git.savannah.gnu.org/git/emacs/elpa.git" :files ("packages/dired-du/*.el") :local-repo "elpa")
```

But of course that will be slower because `straight.el` also has to download and check for modifications all the other packages maintained in GNU ELPA.

**Comment by dieggsy** [comment]
Ah, ok. Thanks!

**Comment by tarsius** [comment]
`dired-du` is in the package database and https://github.com/emacsmirror/dired-du exists.

If this is a fairly recent addition to GNU elpa, then it is missing from the `master` branch of the `epkgs` repository because I have changed the database scheme a bit and since I have done that I have only updated the `next` branch. However I intend to release a new versions of `borg`, `epkg` and `closql` very soon and once I have done that `master` will be fast-forwarded to `next`.
