### ISSUE TITLE
Security concerns about bootstrap code

### ISSUE THREAD

**Issue by diamond-lizard** [raxod502/straight.el#159]
I am concerned about straight.el's bootstrap code unquestioningly running code from the internet.

It's possible that the github account where straight.el is hosted gets compromised, and then if I have the bootstrap code mentioned in straight.el's README in my emacs init, emacs will just run whatever code github serves up without any kind of checks as to its authenticity (no trusted signature checks, for instance) and without any auditing.

Would manually downloading and requiring straight.el in my emacs init work just as well?  I know there are downsides to that, which are mentioned in the README, but at least I'd be able to audit the code myself before I ran it, and I could trust it wouldn't get changed unless I manually downloaded it again.

**Comment by raxod502** [comment]
Yes. You can use the following bootstrap code, if `~/.emacs.d/straight/repos/straight.el` exists and `~/.emacs.d/straight/bootstrap.el` is a symlink to `repos/straight.el/bootstrap.el`:

```elisp
(let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el"))
      (bootstrap-version 2))
  (load bootstrap-file nil 'nomessage))
```

This may not entirely assuage your concerns, however, since anytime you install a package via `straight.el` the same security concerns will come up. I don't think there's any easy way around this—although it might be nice to have a notion of whether repositories are "trusted", so that until you audit them `straight.el` will refuse to run build scripts, byte-compile, or activate autoloads.

**Comment by diamond-lizard** [comment]
Thank you.

A related question:  I noticed that `bootstrap.el` contains this code:

```elisp
;; So meta. This updates the various caches, so that straight.el shows
;; up properly in the lockfile and other things like that.
(straight-use-package '(straight :type git :host github
                                 :repo "raxod502/straight.el"
                                 :files ("straight.el")))
```

If I understand your documentation correctly, this won't ever actually pull the code from github in my case, since it'll already be in `~/.emacs.d/straight/repos/straight.el`, right?

Regarding what you said about me having the same concerns whenever I install a package through `straight.el`, I'm not sure if it'll be quite the same, as `straight.el` will allow me to download the code first, using the `:no-build` directive.  Then I can audit the code, lock it down, and finally build and load it.

The ability to follow this workflow won me over to giving `straight.el` a chance, instead of manually doing everything myself as I have been for years.  In doing package management this way, I won't ever be automatically running any unaudited code from the internet.

**Comment by raxod502** [comment]
Correct.

But `straight.el` won't work perfectly yet with your workflow, since when you go to a new machine, then your packages will be cloned and built automatically. What if they were compromised in the meantime? The solution would probably be to add an option to inhibit checkout when the lockfile revision cannot be found, instead of just printing a warning.

But given your desires, wouldn't it make more sense to manage your packages as submodules of your Emacs configuration? `straight.el` will let you do this. And then you wouldn't have any need for the bootstrap code or on-demand cloning.

**Comment by diamond-lizard** [comment]
Can't I just have `straight.el`'s lockfiles in git?  That way they should pulled in on to my new machine when I clone the git repo that holds my emacs configuration -- or it would if I had one...  that's something I've been meaning to do, but it's all local right now, though checked in to a local git repo.  At this point, if I do move to a new machine, I'd just probably restore from a local backup of my emacs config and go from there.  No complications.

As for managing my packages as git submodules, I've considered using them (or git subtrees, which are supposedly a lot simpler), but was hoping I could make `straight.el` work and have it do all the hard work.

**Comment by raxod502** [comment]
> Can't I just have `straight.el`'s lockfiles in git?

That's the intended use, yes.

> That way they should pulled in on to my new machine when I clone the git repo that holds my emacs configuration

Yes. The repositories for your packages will also be cloned. If the repository was compromised in the meantime, then there would be a problem (for you). The problem might be mitigated, as I said, by making an option to throw an error when the revision specified in the lockfile isn't available in the cloned repository, instead of just printing a warning.

> I'd just probably restore from a local backup of my emacs config and go from there. No complications.

Indeed. The complications I'm talking about are only relevant if you keep your `~/.emacs.d` out of version control, like me.

> git submodules, I've considered using them (or git subtrees, which are supposedly a lot simpler), but was hoping I could make `straight.el` work and have it do all the hard work.

It certainly can, but it's not possible to have a fully automatic bootstrap without either relying on this repository not being compromised, or pushing the work of using submodules (for at least `straight.el`) onto the end user. You can pick and choose how much you would like `straight.el` to manage, depending on your desired use case.

**Comment by diamond-lizard** [comment]
I see now that I'm not going to be able to rely on `straight.el`'s lockfiles to ensure that when code is cloned from a remote repo, that I'm getting the very same code I had previously audited.  For that, I think what would be needed is cryptographic authentication of the entire contents of the checked-out code.

That is, after the code is first checked-out and audited, cryptographic hashes would be made of every file and those hashes stored for future reference.  In the future, if that revision is ever checked out again, new hashes of every file would be made and compared to the hashes already stored before, and if there are any discrepancies the entire checkout would be rolled back atomically.

Since `straight.el` does not currently work like this (if it ever will), I think in the case of a need to move to a new computer, I'll either have to restore the full contents of my `~/.emacs.d` or if I have just my emacs init and `straight.el` in git, I'll just have to re-audit all the code for all the repos `straight.el` clones before allowing it to be built and loaded.

In the meantime I think I will look in to using git submodules or subtrees to integrate all the packages I clone in to my own local git repo, as I see now that that's really the only way I can be sure that the current revision and every previous revision of every package I downloaded has not been changed or tampered with between checkouts.

**Comment by raxod502** [comment]
Sounds good. Although a possible middle ground would be relying on Git's hashing to ensure that nobody tampered with the contents, with the caveat that SHA-1 is technically broken. That is, after all, basically what `git-submodule` is relying on.

**Comment by raxod502** [comment]
Closing since this issue isn't really a bug report or feature request. Please open new issues for things discussed here that you think `straight.el` would benefit from, such as an option to refuse to check out a revision that is not specified in a lockfile.
