### ISSUE TITLE
Automatically update recipe repos

### ISSUE THREAD

**Issue by noctuid** [raxod502/straight.el#179]
If a package recipe isn't found, it would potentially make sense to try updating the recipe repositories and check again.

**Comment by raxod502** [comment]
I don't think this should happen fully automatically, since it would mean that Emacs makes a network call without being told to do so. I would not be opposed to having `straight.el` offer to invoke `M-x straight-pull-package` on the recipe repositories, though.

Under what circumstance are you encountering this problem? Running `M-x straight-use-package` and trying to install a package that was recently added to MELPA, which you heard about from the Internet but which does not appear in the completions list for `straight-use-package`? If this is the case, then there is a UX question: how to find out that the user wants to install a package that isn't listed? It's not like they'll be able to select it if it's not in the list, after all.

**Comment by noctuid** [comment]
Prompting would be fine. Not having to always manually update the recipes would be nice, but this feature would also be nice just to prevent errors (especially during initialization).

I had previously installed straight but just started actually using it today, and this happened to me when switching from package.el. It failed for zoom on initialization. It's fairly often that I install packages that are new on MELPA, and I usually just evaluate a `use-package` form directly. As for interactive usage of `straight-use-package`, I'd think it would be fine to keep it as is. Maybe if it is possible/simple to add a way to take a user's literal input, you could do that (and prompt immediately to update the recipe repos when there is no match).

**Comment by raxod502** [comment]
Certainly I can change the `REQUIRE-MATCH` argument of `completing-read`, but I'm hesitant to do this since the most common case by a very wide margin is installing a package that is already listed.

I'm also hesitant to introduce an interactive prompt directly in `straight-use-package` (i.e. not in interactive usage). Is there an easy way to tell when a form is being evaluated directly by the user?

Although I would be fine putting some more aggressive behavior than currently, if it was behind an option to be enabled.

> prevent errors (especially during initialization)

This shouldn't happen when you port to Emacs configuration to another machine, because you should be using [version lockfiles](https://github.com/raxod502/straight.el#lockfile-management) for your primary Emacs configuration. It should only be a problem interactively.

**Comment by noctuid** [comment]
> Is there an easy way to tell when a form is being evaluated directly by the user?

You could potentially check `called-interactively-p`. If you still require a match (which is fine with me), the only situation in which a package recipe won't be found is non-interactive usage though, correct?

> This shouldn't happen when you port to Emacs configuration to another machine, because you should be using version lockfiles for your primary Emacs configuration. It should only be a problem interactively.

Sure, but that's assuming lockfiles are being used. It's possible that someone else switching to straight.el has the same experience as me because they install straight, continue to use package.el, and then completely switch to straight without first updating the recipe repos manually. Also, if I add a `use-package` statement for a newer package, and then emacs crashes or I restart for whatever reason, initialization will be affected.

**Comment by raxod502** [comment]
> Why?

Because it is suggesting a fix that might not always fix the problem. What if the package was removed, for example? Then you will keep getting this suggestion to update the recipe repositories every time you get an error, even after you've already done it once and it didn't work.

> You could potentially check `called-interactively-p`.

That doesn't work:

```elisp
(defun testing-interactively ()
  (interactive)
  (message "Interactive: %S" (called-interactively-p)))

(testing-interactively)
;; C-x C-e => "Interactive: nil"
```

I think that the reason I am reluctant to do this is because currently, there is no link whatsoever between the repository management layer and the package management layer, and making this change would introduce such a link, hurting modularity.

I would certainly consider merging a pull request which added such a prompt, if it were controlled by an option which is not enabled by default.

**Comment by noctuid** [comment]
> Because it is suggesting a fix that might not always fix the problem. What if the package was removed, for example? Then you will keep getting this suggestion to update the recipe repositories every time you get an error, even after you've already done it once and it didn't work.

Well, it would fix the specific problem I outlined. To prevent infinite prompting in your described case, just prompt/update once. It could potentially first check if the recipe repository is up to date and not prompt at all if it is.

> That doesn't work:

I misunderstood then; evaling anything is non-interactive usage. If you wanted to distinguish between the user evaluating something and something being evaluated, for example, during initialization or by some package, I don't know of a sane/foolproof way to do that.

> I think that the reason I am reluctant to do this is because currently, there is no link whatsoever between the repository management layer and the package management layer, and making this change would introduce such a link, hurting modularity.

I'd say the minor convenience isn't worth it in that case. As for the problem with errors during initialization, a generic solution would be more ideal. I guess jwiegley/use-package#338 is what I want (along with `use-package-check-before-init`). Since straight can obviously be used without use-package, do you think it would make sense to add an option for `straight-use-package` to warn instead of error on failed package installation so that initialization can continue?

**Comment by raxod502** [comment]
> It could potentially first check if the recipe repository is up to date and not prompt at all if it is.

How is it possible to determine if the recipe repository is up to date without fetching?

---

Thinking about it further, I think the real reason I wouldn't want this to be the default behavior is that `straight.el` is not like `package.el`. With `package.el`, it would make a lot of sense to automatically run `package-refresh-contents` when a package is not found, since that is just updating an internal index. However, with `straight.el`, the recipe repository is not just an index: it is, for all intents and purposes, equivalent to a package. You can modify it locally, submit changes upstream, and even build+load Lisp code from a recipe repository. In fact, recipe repositories are registered using `straight-use-package` as well. Would you want `straight.el` to suggest updating a package when you get an error using it? So by analogy, I wouldn't want the same to happen for recipe repositories.

**This said, I will merge a pull request which adds an option to make updating recipe repositories more direct, as long as said option is not enabled by default.**

**Comment by noctuid** [comment]
> How is it possible to determine if the recipe repository is up to date without fetching?

Do a dry run or `git remote update` (and `git status` will show it is behind) or just fetch and don't merge.

> This said, I will merge a pull request which adds an option to make updating recipe repositories more direct, as long as said option is not enabled by default.

Don't get me wrong, I don't think this is worth implementing anymore after hearing your reasoning. I'm more interested in hearing your opinion on this: 

> As for the problem with errors during initialization, a generic solution would be more ideal. I guess jwiegley/use-package#338 is what I want (along with use-package-check-before-init). Since straight can obviously be used without use-package, do you think it would make sense to add an option for straight-use-package to warn instead of error on failed package installation so that initialization can continue?

Is this something you would consider and should I make a new issue for it?

**Comment by raxod502** [comment]
> that may just fetch 

`git remote update` is just a fetch.

> just fetch and don't merge

Right, but fetching is the part that takes the most time (like several seconds). It's also an unsolicited network operation. We can't do it automatically.

> Is this something you would consider

Sure. It requires some thought, however, since there are several ways a package could fail to be loaded. It could have a malformed recipe, there could be a network error, etc.

To be honest, I also don't think this would be very helpful, for the following reason: once again, `straight.el` is not like `use-package`. With `use-package`, you can get an error during initialization if anything is wrong in your user-written configuration code for the package. Thus the primary error condition is you, the user, making a mistake in writing Lisp code. On the other hand, with `straight.el`, there is no user code being run. Nor does an error during byte-compilation halt loading, or any number of other conditions. The only time you actually get an error is when something is really, really wrong: the repository that the package needs to be fetched from does not exist, or the recipe is malformed, or specifies a self-contradictory `:files` directory, and so on. These seem like pretty severe errors. And there is certainly no way for `straight.el` to recover from them, other than just doing nothing: the recovery will have to be at a higher level. If you're using `use-package`, then the recovery would be https://github.com/jwiegley/use-package/issues/338. If you're using `straight.el` manually, I would assume you would do something like

```elisp
(dolist (package all-my-packages)
  (with-demoted-errors
    (straight-use-package package)))
```

so that the error handling is still outside of `straight.el`.

> should I make a new issue for it?

Sure, if you still think it would be useful. I'm happy to consider it if someone provides the patch.

**Comment by noctuid** [comment]
Fair enough. It probably makes more sense for this to be something the user decides to do, and it's easy enough for me to just advise the ensure function.
