### ISSUE TITLE
Get current stable org

### ISSUE THREAD

**Issue by mclearc** [raxod502/straight.el#189]
Is there a way to use straight.el to get the current stable org (i.e. what one would download from elpa, currently org 9.1.3)? Sorry if this is a silly question.

**Comment by raxod502** [comment]
In principle, it is as simple as navigating to the Org-mode repository (most likely, `~/.emacs.d/straight/repos/org`—but `M-x find-library` on any Org-related file will also get you there) and performing a `git checkout` on the appropriate revision.

In practice, this is somewhat complicated by the fact that, by default, `straight.el` pulls Org from the EmacsMirror, and the resulting repository does not include tags. Therefore, you would have to either identify the commit manually, or get a separate copy of the Org repository and copy the revision ID. For Org 9.1.3, this is:

```
946f76d7070f8fbcf5c1072b7f53cea599f2e110
```

You can always pull Org from its source repository using `straight.el`, and thereby obtain the tags, with a custom recipe:

```
(org :type git :repo "git://orgmode.org/org-mode.git")
```

The disadvantage in this is that the official Org repository does not appear to offer HTTPS, for some reason. Thus you would need to verify the GPG signature on the tag in order to assure that the result is authentic.

The user experience can be improved in three ways:

* adding support to `straight.el` for automatically checking out a tag instead of the latest revision, if no lockfile is present (see #31)
* determining why EmacsMirror drops tags (I have not investigated this)
* determining whether Org is available in some official (non-mirror) capacity via HTTPS (I have not investigated this)
* adding information about this to the documentation

**Comment by mclearc** [comment]
Thanks very much for the thorough and helpful reply. I had been looking through the commits and been confused as to why there were no tags. I didn't realize that EmacsMirror drops them. But now that I know this it won't be hard to look up the commit when a new version is released, or until straight.el adds support for checking out tags. :) And thanks for the awesome work you're doing!

**Comment by kevinjfoley** [comment]
FYI it looks like the org source repo moved servers for 2018 and the new server supports https, the new repo URL per https://orgmode.org/worg/dev/ is https://code.orgmode.org/bzg/org-mode.git

**Comment by raxod502** [comment]
Yes, thanks. I fixed that in https://github.com/raxod502/straight.el/commit/25a978830a78ecd73a89c355da47d3dc482aab64.
