### ISSUE TITLE
Does not appear to handle detached head correctly

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#194]
When I detach the HEAD of a repository at some commit other than the primary branch, `straight.el` insists that the HEAD is actually even with said primary branch.

**Comment by holgerschurig** [comment]
Maybe similar: when I bootstrapped with `(setq straight-repository-branch "develop")` it created repos/straight.el correctly. But when I manually switched there I couldn't just "git pull". The remote wasn't set either. And so I think that this behavior might fit into this bug, because it's a general "how to setup the git repo" thingy, or?

**Comment by raxod502** [comment]
@holgerschurig Can you open a separate issue for that, if you can reproduce the problem? It sounds like a different bug (or unclear documentation).

**Comment by progfolio** [comment]
Fixed by #711
