### ISSUE TITLE
straight-use-package-ensure-function has the wrong number of arguments

### ISSUE THREAD

**Issue by katandtonic** [raxod502/straight.el#200]
I am getting this traceback with the latest versions of straight.el and use-package.

```
Debugger entered--Lisp error: (wrong-number-of-arguments (4 . 5) 3)
  straight-use-package-ensure-function(org (t) nil)
  eval-buffer(#<buffer  *load*> nil "/Users/kathuang/.emacs.d/init.el" nil t)  ; Reading at buffer position 2689
  load-with-code-conversion("/Users/kathuang/.emacs.d/init.el" "/Users/kathuang/.emacs.d/init.el" t t)
  load("/Users/kathuang/.emacs.d/init" t t)
  #[0 "\205\266	\306=\203\307\310Q\202?	\311=\204\307\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB\323\202?\316\324\325\324\211#\210\324=\203e\326\327\330\307\331Q!\"\325\324\211#\210\324=\203d\210\203\247\332!\333\232\203\247\334!\211\335P\336!\203\201\211\202\214\336!\203\213\202\214\314\262\203\245\337\"\203\243\340\341#\210\342\343!\210\266\f?\205\264\314\325\344\324\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()
```

It seems that `straight-use-package-ensure-function` requires too many arguments

(https://github.com/raxod502/straight.el/blob/d295fd9edef728caf3f81e321b35cd2ffa303127/straight.el#L4227)

This comment seems to indicate that the function should take only 3 arguments.
https://github.com/jwiegley/use-package/blob/b1c105a9e4093be4e159f0a7df9da9bb5bb03c60/use-package-ensure.el#L61

```
(defun straight-use-package-ensure-function
          (name ensure state context &optional only-if-installed)
```

I suspect that I am missing something as @raxod502 should probably be aware of this fact, given that he is the one that edited this docstring:

https://github.com/jwiegley/use-package/commit/4f483b6f5171819779cbc8836feeacacfef5ed55

What am I missing here?

**Comment by katandtonic** [comment]
Ahh, seems that maybe what is going on is that integration with the new version of use-package lives on develop? 

This creates a not great user experience imo...

**Comment by raxod502** [comment]
Yes, the bug was only fixed on `develop`. If you were using `master` then it would not work with the latest version of `use-package`. Since this will probably be a frequent problem I have updated `master` to include this fix. Let me know if it is still not working.

**Comment by katandtonic** [comment]
@raxod502 Yeah, got things working by simply using develop branch. Is that the recommended way to do things?

The recent use-package/straight changes kinda caused a lot of upheaval. I am aiming for a pretty stable experience that I don't need to worry about a ton.

**Comment by raxod502** [comment]
There are three different relationships you could have with `straight.el`:

1. You were using it before `use-package` was updated, but with no version lockfile.
2. You were using it before `use-package` was updated, and you have a version lockfile.
3. You had never used `straight.el` before, and so installed the latest version of `use-package`.

In situation 1, it's your own fault; the whole point of having a version lockfile is so that package updates don't break your configuration.

In situation 2, there's no problem, since you'd have to explicitly update `use-package` and presumably when you did this you would also make sure all the other packages in your configuration were compatible with the new version. In this case, you would either wait until compatibility with the new `use-package` was merged to `master`, or switch to `develop` in the meantime. (The latter option, thankfully, is much easier now that #186 is fixed.)

In situation 3, there's definitely a problem but unfortunately there's no general solution other than me trying to be quick about responding to changes that break the out-of-the-box user experience. Anyone who tried out `straight.el` and `use-package` for the first time over the last few days just got unlucky. I don't think this situation will happen very often, though.

Does that answer your question?
