### ISSUE TITLE
Option for suppressing 'foo-autoloads' features from being defined

### ISSUE THREAD

**Issue by holgerschurig** [raxod502/straight.el#202]
Currently straight.el is creating FOO-autoloads.el files that "(provide FOO-autoloads)" themselves. And I gess they get loaded with "(require FOO-autoloads").

However, this inflates the variable "features", it's now much harder to see which modules are actually loaded than before. BTW, package.el doesn't do this either.

I actually think that autoload files never depend on each other, so there is no need to "(require" them. Instead, you can simply (load "FOO-autoloads") them, or?

**Comment by raxod502** [comment]
I looked into this, and creating files which `provide` the `FEATURE-autoloads` feature is the default behavior of `autoload.el`. In fact, `package.el` does an interesting hack whereby they create autoload files with a custom template, and then invoke `update-directory-autoloads` in order to _update_ the template. The template used by `package.el` is quite similar to the default one from `autoload.el`, with only a few modifications.

Before making any such modification in `straight.el`, I'd need to understand why `package.el` makes this change—and why `autoload.el` inserts the `provide` forms in the first place (maybe if I remove this, it will break some other packages). If there isn't a good reason, I'd like to stick to the defaults.

**Comment by raxod502** [comment]
By the way, this has nothing to do with how the autoloads are evaluated. In fact, if you [look at the source code of `straight.el`](https://github.com/raxod502/straight.el/blob/0e9d8af882972dd8ae7755595e5b064beefbbe41/straight.el#L3507-L3528) you'll find that it uses `load`, not `require`.

**Comment by raxod502** [comment]
I suppose I'm not opposed to adding an option for this, at least. It wouldn't be too hard, I think. It won't happen until after the 1.0 release, most likely.

**Comment by progfolio** [comment]
I don't think this is a high-demand feature. If more requests for this feature come in, we can reconsider. Closing for now.
