### ISSUE TITLE
Is the doc-string of straight-enable-use-package-integration outdated?

### ISSUE THREAD

**Issue by xuchunyang** [raxod502/straight.el#209]
I use `package.el` + `use-package` and now I want to try `straight.el`. I have changed `package.el`'s bootstrap code into `straight.el`'s., then do I need to query-replace all my `:ensure ...` into `:straight ...`? It seems not necessary according to the doc-string of `straight-enable-use-package-integration` (defaults to `t`):

https://github.com/raxod502/straight.el/blob/0e9d8af882972dd8ae7755595e5b064beefbbe41/straight.el#L321-L329

but Emacs still errors

> error: package.el is not yet initialized!

I also don't understand `straight-use-package-version`, is it rely on the version of `use-package`? I'm going to use latest version of `use-package`, I try to set it to `'ensure` before `straight.el` is loaded, but it seems not working as well.

**Comment by raxod502** [comment]
That docstring was fixed in commit https://github.com/raxod502/straight.el/commit/11def4e89aeb9722817524f0b9ca33636571fc4b which was only available on branch `develop` and not `master`, sorry. I have now merged it into `master`.

`(setq use-package-always-ensure t)` should be replaced with `(straight-use-package-by-default +1)`, and `:ensure` should be replaced with `:straight`, as you suspected.

**Comment by raxod502** [comment]
As for `straight-use-package-version`, if you are using the latest version of `use-package` then the default value is what you want, as per

https://github.com/raxod502/straight.el/blob/4e76d3b025b4306e6a2159e127314beb40dd9acd/straight.el#L4463

The reason this variable exists is that `use-package` was completely refactored and this meant the syntax for the integration provided by `straight.el` needed to change in a backwards-incompatible way.

**Comment by xuchunyang** [comment]
I know `:straight` works. What I want is keeping using `:ensure` without changing to `:straight`, I consider it as a feature, is it supported?

The following fails from here, is the failure expected?

 > error: package.el is not yet initialized! 

```
(setq straight-use-package-version t)

(let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el"))
      (bootstrap-version 2))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(use-package diminish
  :ensure t)
```

**Comment by xuchunyang** [comment]
After taking a look at the implementation `straight-use-package-mode`, it assumes the feature `use-package`, however the feature is not loaded at all, thus manually `(require 'use-package)` fix the problem for me.

```
(setq straight-use-package-version 'ensure)

(let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el"))
      (bootstrap-version 2))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(require 'use-package) ; <= because of how `straight-use-package-mode' works

(use-package diminish
  :ensure t)
```

**Comment by raxod502** [comment]
> What I want is keeping using `:ensure` without changing to `:straight`, I consider it as a feature no matter what , is it supported?

Using `:ensure` with the most recent version of `use-package` is not officially supported. (Because overriding `:ensure` makes it impossible to use `use-package` with both `package.el` and `straight.el` in the same configuration.) You can nevertheless obtain this behavior as follows:

```elisp
(defalias 'use-package-handler/:ensure #'use-package-handler/:straight)
(defalias 'use-package-normalize/:ensure #'use-package-normalize/:straight)
```

> The following fails from here, is the failure expected?

If you are using the most recent version of `use-package`, then your configuration is not supported, since you have configured `straight-use-package-version` to indicate that you are using an _old_ version of `use-package`. I do not know immediately why you got the specific error you did, though.

> ```
> (require 'use-package) ; <= because of how `straight-use-package-mode' works
> ```

This is only necessary because the value of `straight-use-package-version` is incompatible with the version of `use-package` in use. If you either downgrade `use-package` or correct the value of `straight-use-package-version`, then a manual `require` will not be necessary.

**Comment by xuchunyang** [comment]
I see, thanks for your help.
