### ISSUE TITLE
Recipes from EmacsMirror repository do not always work

### ISSUE THREAD

**Issue by xuchunyang** [raxod502/straight.el#226]
Currently recipes from the EmacsMirror repository use the default file list, but no one can ensure it is always correct, unlike Melpa.  For example, I install debbugs with `(straight-use-package 'debbugs)` then I notice I can't use this package because `Debbugs.wsdl` is missing. In the end, I have to modify the recipe by adding this file into `:files` keyword:

```el
(straight-use-package
 '(debbugs :type git :host github :repo "emacsmirror/debbugs"
           :files (:defaults "Debbugs.wsdl")))
```

**Comment by raxod502** [comment]
Can this be solved by mirroring the logic used by https://github.com/emacscollective/borg to build packages more closely? If not, I'm not sure what can be done. I'm open to suggestions. (Maybe #115 will help with the problem since you wouldn't have to rely on EmacsMirror as much.)

**Comment by xuchunyang** [comment]
I don't know about borg, but if we build package within the git repo, i.e., `~/.emacs.d/straight/repos/debbugs/` instead of `~/.emacs.d/straight/build/debbugs/`, it will works fine.

**Comment by raxod502** [comment]
This is a bad idea in general. I considered it about a year ago, at the very beginning. But doing in-place builds introduces a number of problems:

- You must modify `.git/info/exclude` automatically, otherwise you end up with a dirty working directory
- You must add multiple directories to `:load-path` potentially
- It's not compatible with MELPA recipes

Now it might be reasonable to add an _option_ for this that could be enabled as part of a package's recipe. But given that linking is not usually a bottleneck I think it would make more sense to have an option for the `:files` directive to link _all_ files, except some ones that are specified.

Note also that this reasoning is not incompatible with packages like Org that have custom build steps that do byte-compilation and autoload generation. There can be recipe options that (1) allow for running `make` or another command in the Git repo on build, and (2) link `.elc` and autoload files into the build directory, instead of generating them (actually this is already handled by our `:files` logic and your contributions along the lines of making sure `straight.el` doesn't overwrite generated files if they were linked from the Git repo).

**Comment by xuchunyang** [comment]
> it would make more sense to have an option for the :files directive to link all files, except some ones that are specified.

How about `("*" :defaults)`? It seems it is doing this.

However, without verification in advance, any assumption on how to build and install a package still can be wrong, I think It is necessary to take a look at the packages one by one to find out how to handle each package correctly, though I don't know how.

**Comment by raxod502** [comment]
I believe (though @tarsius may correct me) that the heuristics used in Borg are intended to be only that—heuristics. Thus some packages will not build correctly by default, and this is a bug in those packages, since they don't follow conventions. I believe Borg has options that allow the user to specify custom build instructions for individual packages if those packages are not fixed upstream, but I don't think there's any support for a sort of "recipe repository" that everyone would share.

All the more reason to include el-get as well: the more recipe repositories that are _guaranteed_ to provide valid recipes, before we drop down to EmacsMirror which only works _most_ of the time (although it's never failed for me—you must use much more interesting packages than I), the better.

Nevertheless, since we already have only heuristics for EmacsMirror recipes, I'd welcome any changes that make the heuristics work in more cases.

**Comment by tarsius** [comment]
That sounds about right, though a few packages that cannot be build using these heuristics don't actually have any bugs. `org` and `mu4e` are good examples - their complexity justify the need for explicit build steps.

I am considering adding support for a recipe repository but currently the only way to distribute the custom build steps of some package is to create a branch for that package that others can merge into their configuration.

**Comment by progfolio** [comment]
Closing now that we have support for arbitrary `:pre-build` commands (covers the case of packages like `org` and `mu4e`) and el-get recipe support. If anyone feels there is anything actionable we can add from this issue feel free to comment/reopen.
