### ISSUE TITLE
Display "Rebuilding" in message if package was already built

### ISSUE THREAD

**Issue by triklsbg** [raxod502/straight.el#239]
> Building use-package...
> Building use-package → Building bind-key...done
> Building use-package...done
> Building org...done
> Building undo-tree...done
> Building diminish...done

I was surprised by this sparse messages after i installed straight yesterday. I recognized a short unexpected hibernation after starting emacs and asked me why  "Building ... org " happens. A short hint in the message buffer how to toggle to non-auto refreshing would be useful.

PS: Thanks!!! for making straight and the rich documentation which i didn't reread before issuing this.

**Comment by raxod502** [comment]
Sorry, I don't understand. Are you suggesting to print `Rebuilding` instead of `Building` when packages had been previously built?

> A short hint in the message buffer how to toggle to non-auto refreshing would be useful.

By "non-auto refreshing" do you mean that a package is rebuilt after you modify it? This is behavior that pretty much everyone except _extreme_ power users or people in niche use cases (no access to `find(1)`, for example) would want.

**Comment by dieggsy** [comment]
@raxod502  seems about the message, they just mean that the source of it is ambiguous, and suggest to use something like `straight is building undo-tree...` rather than `building undo-tree`.

**Comment by raxod502** [comment]
It seems to me that the benefit of additional clarity in the message would be pretty small. I just don't see in what situation one wouldn't realize the source of the message. You see it pretty often when using `straight.el`, and not otherwise—when it would it not be clear that it's a `straight.el` message?

Maybe I'm missing a common use case? It's happened before :)

**Comment by xendk** [comment]
I think they match use-package' `Loading package...` very well. But I would like if it said `Rebuilding...` if that's not too difficult. Seems more fitting.

**Comment by dieggsy** [comment]
@raxod502 to clarify, I mostly have no problem with the messages myself

**Comment by raxod502** [comment]
@xendk Fair enough, I think this could be done within the current build system context. The correct way would probably be to key off the list of previously loaded packages that is written to the build cache after a successful init, although I'm not sure about this.

**Comment by progfolio** [comment]
> It seems to me that the benefit of additional clarity in the message would be pretty small. I just don't see in what situation one wouldn't realize the source of the message.

I agree.
Closing, but feel free to reopen if you feel it's worth it.
