### ISSUE TITLE
Live modification checking does not notice repository management commands

### ISSUE THREAD

**Issue by xendk** [raxod502/straight.el#242]
Creating this for completeness, as I've reverted to at-statup (got an SSD, so I'd probably get more out of deferring more package loads).

**Comment by raxod502** [comment]
Just to be clear (unless I misunderstand), this is not a problem with `straight-check-package` but with the live modification checking system itself—packages are simply not detected as modified when they are touched by the repository management commands. I do not think this should be hard to fix.

**Comment by raxod502** [comment]
See also https://github.com/raxod502/straight.el/pull/241#issuecomment-367914925.

**Comment by xendk** [comment]
Well, yeah. Though a case could be made for explicitly running `straight-check-(package|all)` should check modifications time anyway (I don't believe that the check straight does at startup uses them?).

I guess those functions would also be the only way for those using live modification check to catch changes from outside Emacs, without having to explicitly provide package names to rebuild.

**Comment by raxod502** [comment]
> Though a case could be made for explicitly running `straight-check-(package|all)` should check modifications time anyway

I could consider that, but part of the reason I introduced live modification checking, other than performance, is that not everyone has access to `find(1)`. (Hello, Windows.)

> I don't believe that the check straight does at startup uses them

Of course not, if you're using live modification checking. Otherwise there would be no need for detecting modifications live.

> I guess those functions would also be the only way for those using live modification check to catch changes from outside Emacs

This is a valid point since there is currently no support for this use case. I think the API (currently just `straight-check-for-modifications` needs to be made a little richer to account for the case where you usually use live modification checking, but you do have `find(1)` and sometimes want to use it.

**Comment by raxod502** [comment]
I believe this addresses all of your concerns. The repository management commands will now result in live modification detection, same as if you had edited the buffer (but only if the commands actually had an effect on the files in the repository). And you can customize `straight-check-for-modifications` to `live-with-find` to allow `straight-check-package` and `straight-check-all` to use `find(1)` even though it's not used at startup.
