### ISSUE TITLE
use-package not properly installing

### ISSUE THREAD

**Issue by Ultramann** [raxod502/straight.el#250]
I'm really not quite sure what the origin of this issue is so I'll do my best to describe all the symptoms I can observe.

I'm experimenting with emacs having been in vim for the last decade, consequently I'm attempting to use `straight.el` to install `evil` and `evil-leader`. In addition it means that I'm very ignorant of emacs, it's way of doing things and emacs-lisp. I'll start off by enumerating everything I can imagine might matter.

I'm running GUI Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) on High Serra 10.13 that was installed with `brew cask install emacs`.

My init file to do so looks as follows (truncated to show minimal content to produce issue):

```el
(let ((bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 3))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(eval-and-compile (require 'straight))

(package-initialize)
(straight-use-package 'use-package)

(setq custom-file "~/.emacs.d/custom.el")
(load custom-file 'noerror)

(defun switch-to-previous-buffer ()
  "Switch to previously open buffer."
  (interactive)
  (switch-to-buffer (other-buffer (current-buffer) 1)))

(defun config-evil-leader ()
  "Configure evil leader mode."
  (evil-leader/set-leader "<SPC>")
  (evil-leader/set-key
   "u" 'redo
   ))

(use-package evil
  :straight t
  :commands (evil-mode evil-define-key)
  :config
  (evil-mode 1)
  (use-package evil-leader
    :straight t
    :config
    (global-evil-leader-mode)
    (config-evil-leader)))

(provide 'init)
```

If I start emacs with no `straight` directory in `.emacs.d`, straight exhibits the, what I expect to be, correct behavior. It enumerates the packages it is installing, namely `use-package`, `evil` and `evil-leader`. Once everything is installed I get the emacs splash screen which I can correctly navigate with vim bindings but there is a split below it with warnings. Below is a sample of lines from the warnings, I won't repeat like ones to save space.

```
Warning (straight): Command failed: makeinfo /Users/ultramann/.emacs.d/straight/repos/use-package/use-package.texi -o /Users/ultramann/.emacs.d/straight/build/use-package/use-package.info (default-directory: "/Users/ultramann/.emacs.d/straight/repos/use-package/"):
/Users/ultramann/.emacs.d/straight/repos/use-package/use-package.texi:6: warning: unrecognized encoding name `UTF-8'.
/Users/ultramann/.emacs.d/straight/repos/use-package/use-package.texi:299: `@code{after}' has no Up field (perhaps incorrect sectioning?).
/Users/ultramann/.emacs.d/straight/repos/use-package/use-package.texi:278: Menu reference to nonexistent node `after}: @code{after}' (perhaps incorrect sectioning?).
/Users/ultramann/.emacs.d/straight/repos/use-package/use-package.texi:87: Cross reference to nonexistent node `after}: @code{after}' (perhaps incorrect sectioning?).
/Users/ultramann/.emacs.d/straight/repos/use-package/use-package.texi:299: warning: unreferenced node `@code{after}'.
makeinfo: Removing output file `/Users/ultramann/.emacs.d/straight/build/use-package/use-package.info' due to errors; use --force to preserve.
```

If I exit Emacs and then start it back up I get the splash screen again, no warnings, but evil bindings are not working.

I've repeated this sequence of events multiple times by removing the `straight` directory and starting the process over.

I'm guessing I'm messing up something trivial and my Emacs inexperience is preventing me from seeing it, so any help will be greatly appreciated.

**Comment by xuchunyang** [comment]
> Warning (straight): Command failed: makeinfo /Users/ultramann/.emacs.d/straight/repos/use-package/use-package.texi -o /Users/ultramann/.emacs.d/straight/build/use-package/use-package.info (default-directory: "/Users/ultramann/.emacs.d/straight/repos/use-package/"):

It fails because `use-package.texi ` doesn't support Mac's built-in `/usr/bin/makeinfo`, it requires a newer version of Texinfo. I've report this to use-package in https://github.com/jwiegley/use-package/issues/609. It is a warning and it means you can't see the info manual of use-package, but use-package still could be useable. I wanted straight.el to emit a warning because I switched to straight.el from package.el, I notice some info manuals were missing.

> If I exit Emacs and then start it back up I get the splash screen again, no warnings, but evil bindings are not working.

Maybe you need to fix your use of use-package, in the following, `evil-mode` won't be enabled when Emacs starts

```el
(use-package evil
  :straight t
  :commands (evil-mode evil-define-key)
  :config
  (evil-mode 1)
  (use-package evil-leader
    :straight t
    :config
    (global-evil-leader-mode)
    (config-evil-leader)))
```

**Comment by Ultramann** [comment]
@xuchunyang Thanks for the quick reply! The instructions in the issue you linked did the trick. I guess I'll go figure out why `(evil-mode 1)` isn't enabling evil as I thought it was...

**Comment by raxod502** [comment]
I noticed several things.

---

```elisp
(eval-and-compile (require 'straight))
```

This is unnecessary; the bootstrap snippet always loads `straight.el` as far as I know (although I haven't tested with a byte-compiled init file).

---

```elisp
(package-initialize)
```

That loads `package.el`. If you're using `straight.el` then you almost certainly don't want this.

---

```elisp
(defun switch-to-previous-buffer ()
  "Switch to previously open buffer."
  (interactive)
  (switch-to-buffer (other-buffer (current-buffer) 1)))
```

You can accomplish the same as `M-x switch-to-previous-buffer` with just `C-x b`; the previous buffer is automatically selected.

---

```elisp
  :commands (evil-mode evil-define-key)
```

This is unnecessary, since `straight.el` defines evaluates the autoloads of `evil` and you don't need to create them with `use-package`.

---

```elisp
  :config
  (evil-mode 1)
```

This is almost certainly not what you want. It means that `evil-mode` is enabled automatically, but only after the package file is loaded. I am assuming that you want `evil-mode` to be enabled unconditionally, at Emacs startup. I would recommend the following instead:

```elisp
(use-package evil
  :straight t
  :demand t
  :config
  (evil-mode 1))

(use-package evil-leader
  :straight t
  :demand t
  :config
  (global-evil-leader-mode)
  (config-evil-leader))
```

---

You may ask why the behavior differed on initial startup versus later sessions. This is because when `straight.el` builds a package, it byte-compiles it, and this usually causes the package to be loaded. This triggered your `:config` clause.

The warnings were not printed because they are triggered when the package is built. You can see that for yourself using `M-x straight-rebuild-package`.

**Comment by Ultramann** [comment]
@raxod502 Thanks for the advice! Everything worked like a charm. Awesome package you're developing here. Removes (nearly all of) the pain I manually managed with git submodules in vim.

**Comment by raxod502** [comment]
Also, I don't think having texinfo failures printed directly to the main warnings buffer is good UX @xuchunyang, since there are many packages that can't yet be handled correctly by `straight.el`, through no fault of the end user. Perhaps we could use something like https://github.com/raxod502/straight.el/issues/208#issuecomment-356704371, and then print a more human-readable message saying `Compiling texinfo for <package> failed; see *straight-build*`.

I'm not saying you have to make the change, just thought I would put the idea out there.
