### ISSUE TITLE
Clarifications on recipe handling

### ISSUE THREAD

**Issue by Jean-MichelC** [raxod502/straight.el#260]
Hello,

I'm a user of emacs but not a programmer. I make a heavily use of org-mode for professional reasons. Your project straight.el is very interesting (as my linux of choice is nixos).
The documentation of straight.el is very comprehensive. However some things that should be clarified IMHO : 
- is (straight-use-package '(some-package...)...) strictly equivalent to (use-package some-package :straight ...) ?
- does (use-package some-package :straight (some-package :host git ....) makes absolutely sure that some-package is downloaded from git ?

Thanks, and sorry if this is not properly an issue, I could ask the question on another channel if you prefer ...

**Comment by raxod502** [comment]
> is (straight-use-package '(some-package...)...) strictly equivalent to (use-package some-package :straight ...) ?

Unless you change `use-package-always-defer` from its default value of `nil`, the `use-package` form will also cause the feature to be required. This is a property of `use-package`, however, and should be covered in the documentation for `use-package`.

Otherwise, the behavior is covered in the section [Integration with `use-package`](https://github.com/raxod502/straight.el/tree/3ed35b94c843815440eb943e2ccaeb152a3d2838#integration-with-use-package-1) and in the documentation of the variable `straight-use-package-version`. Namely, the value passed to `straight-use-package` is determined as follows:

* if `:straight` not provided and `straight-use-package-by-default` is nil, or `:straight nil` given, then `straight-use-package` is not called
* if `:straight` not provided and `straight-use-package-by-default` is non-nil, or `:straight t` given, the feature name is used
* if `:straight <symbol>` or `:straight (<symbol> :keyword <arg>...)` given, then the argument to `:straight` is used
* if `:straight (:keyword <arg>...)` given, then the argument to `:straight` is prepended with the feature name and then used.

What documentation changes would you suggest?

> does (use-package some-package :straight (some-package :host git ....) makes absolutely sure that some-package is downloaded from git ?

If you are concerned that it might be necessary to clone the repository manually, then no, this is always done automatically. The process is covered in the section [Installing packages programmatically](https://github.com/raxod502/straight.el/tree/3ed35b94c843815440eb943e2ccaeb152a3d2838#installing-packages-programmatically). Again if you have suggestions on how the documentation could be improved, I would be happy to hear them.

> sorry if this is not properly an issue, I could ask the question on another channel if you prefer

No problem. I don't yet have enough issues to need a policy on acceptable issue types.

**Comment by Jean-MichelC** [comment]
Thanks for the very exhaustive answer;

First point : 
I would suggest, in the [integration-with-use-package](https://github.com/raxod502/straight.el/tree/3ed35b94c843815440eb943e2ccaeb152a3d2838#integration-with-use-package-1) section, to add at the end of 

>

>  This:
> (use-package el-patch
>   :straight t)
> becomes:
> (straight-use-package 'el-patch)
to add : "making both forms strictly equivalent"
and maybe replace "becomes" with "becomes when executed" 

second point :
in fact my concern is more avoiding to download from melpa or other sources. I'd like to be sure that (use-package some-package :straight (some-package :host git ....)) installs from git excluding other sources : could you confirm ?

**Comment by raxod502** [comment]
> to add : "making both forms strictly equivalent"

The forms are _not_ "strictly equivalent", for the reasons I mentioned above (including `use-package-always-defer` and other settings). That's why I didn't say so in the documentation. If you are really curious to see exactly what it expands to, you can use `M-x pp-macroexpand-last-sexp`.

> and maybe replace "becomes" with "becomes when executed"

I replaced it with "macroexpands (essentially) to" since Emacs Lisp does not really speak of "executing" code, but rather macroexpanding, interpreting, evaluating, or compiling it.

> in fact my concern is more avoiding to download from melpa or other sources

The _only_ way packages can be installed by `straight.el` is using Git. Recipes are taken from MELPA if not given, but the packages are cloned independently.

**Comment by Jean-MichelC** [comment]
I'm starting to understand ... however, you say here 

> "The only way packages can be installed by straight.el is using Git."

But in [installing-packages-programmatically](https://github.com/raxod502/straight.el/tree/3ed35b94c843815440eb943e2ccaeb152a3d2838#installing-packages-programmatically) I read :

> Out of the box, you can install any package from MELPA or EmacsMirror,
which is IMHO sort of confusing, at least for me.

I also read elsewhere:
> If the local Git repository for el-patch is not available, it is cloned,

and [https://github.com/raxod502/straight.el#conceptual-overview](url):

> straight.el operates by cloning Git repositories 

which is clear

My suggestion would be to change the first sentence into something like:

> Out of the box, you can install any package _present in_ MELPA or EmacsMirror,_using a git mechanism_

Back to my question, and making clearer: what is the way to make sure you never use code from melpa/elpa/EmacsMirror and instead always use code from GitHub ? in order to make that sure, is it enough to use systematically a recipe such as 
`(el-patch :type git :host github :repo "raxod502/el-patch")`

**Comment by raxod502** [comment]
I can see how that wording would be confusing. I changed it.

> what is the way to make sure you never use code from melpa/elpa/EmacsMirror and instead always use code from GitHub ?

The answer is still: the _only way that packages can be installed_ is via Git. The only thing MELPA is used for is for getting recipes, not built packages. There is simply no way at all that you could install a package _without_ using Git, because the logic for doing that does not exist in `straight.el`. It doesn't matter whether you use

```elisp
(straight-use-package 'el-patch)
```

or

```elisp
(straight-use-package '(el-patch :host github :repo "raxod502/el-patch"))
```

because they both do the same thing (assuming the recipe for `el-patch` isn't changed on MELPA).

**Comment by Jean-MichelC** [comment]
I'm starting to understand ... however, you say here 

> "The only way packages can be installed by straight.el is using Git."

But in [installing-packages-programmatically](https://github.com/raxod502/straight.el/tree/3ed35b94c843815440eb943e2ccaeb152a3d2838#installing-packages-programmatically) I read :

> Out of the box, you can install any package from MELPA or EmacsMirror,
which is IMHO sort of confusing, at least for me.

I also read elsewhere:
> If the local Git repository for el-patch is not available, it is cloned,

and [https://github.com/raxod502/straight.el#conceptual-overview](url):

> straight.el operates by cloning Git repositories 

which is clear

My suggestion would be to change the first sentence into something like:

> Out of the box, you can install any package _present in_ MELPA or EmacsMirror,_using a git mechanism_

Back to my question, and making clearer: what is the way to make sure you never use code from melpa/elpa/EmacsMirror and instead always use code from GitHub ? in order to make that sure, is it enough to use systematically a recipe such as 
`(el-patch :type git :host github :repo "raxod502/el-patch")`

**Comment by Jean-MichelC** [comment]
I made a mistake : please delete the last comment

**Comment by Jean-MichelC** [comment]
Perfectly clear now. thanks.

**Comment by raxod502** [comment]
Glad to hear it. I made some more updates to the documentation to hopefully make it more clear that packages which are listed on MELPA are installed using Git, rather than there being some kind of option to either install packages from MELPA versus install packages using Git.
