### ISSUE TITLE
Is there support for removing packages?

### ISSUE THREAD

**Issue by nrvale0** [raxod502/straight.el#272]
Looking at the docs, I think no. Deleting the directory from the build cache causes problems at next start and the only solution I've found (in another ticket) is to delete the build cache completely and re-init.

**Comment by raxod502** [comment]
Define "remove". If you do not explicitly request for a package to be made available in your init-file (via `(straight-use-package ...)`), then it will not be made available, end of story. It is not like in `package.el`, where there is some notion of "installed packages", which are made available unconditionally unless you "remove" them.

If you want to free the disk space, then after you remove the request for the package from your init-file, you can delete the local repository in `~/.emacs.d/straight/repos`.

**Comment by raxod502** [comment]
As an addendum, the user _should_ never have to do anything with the build cache. There is even automatic support for invalidating it when the schema changes in a new version of `straight.el`. The only time you would have to mess with it is if I, as the developer of `straight.el`, mess up.

**Comment by nrvale0** [comment]
I did an rm -rf of a git repo in the build cache and then restarted emacs and got a complaint about the missing directory. Unfortunately I do not have the error message as I just blew away build-cache.el and restarted again and everything is happy now. That felt like Really Bad Behavior(TM) but I didn't see anything in the docs about better ways. Thus the Q.

**Comment by nrvale0** [comment]
You're correct. I mis-stated that it was in the build cache. 

To be clear:

1. remove ~/emacs.d/init.el reference to the package to be removed
1. rm -rf repo dir
1. stop emacs
1. restart emacs
1. get error message about missing package repo dir

If build-cache.el is built/updated as part of the emacs shutdown then it makes sense it would generate an error message at the next start. Which I believe is what you are saying.

In any case, I'm not an elisp hacker but perhaps I'll make a pass at a ```(straight-use-package <name> :rm ...)``` or something similar.

**Comment by raxod502** [comment]
> If build-cache.el is built/updated as part of the emacs shutdown then it makes sense it would generate an error message at the next start. Which I believe is what you are saying.

Not exactly, no. The build cache is updated during startup. To detect package modifications, all packages that were used during the last startup are checked in a single operation; this improves performance. Due to a bug in the implementation of this optimization, if one of the packages that was used during the last startup has had its local repository removed from disk since then, it will throw an error. However, if you complete a startup that did not use the package to be deleted, before actually deleting it, the error is avoided.

This analysis agrees with the observations you outlined.

You can read the code here: https://github.com/raxod502/straight.el/blob/9e136a7b72b8487a4d70d226fe9743b29a2dda27/straight.el#L2576-L2673

> In any case, I'm not an elisp hacker but perhaps I'll make a pass at a `(straight-use-package <name> :rm ...)` or something similar.

I don't think that's the correct solution. This is just a bug with the implementation of the modification checker, plain and simple. (There is the separate question of providing an interactive command to delete a package's local repository, but it doesn't seem like a huge priority to me since (unlike with `package.el`) doing so doesn't get you anything but a few more MB of disk space.)

---

Also, I finally see that I misread your original question "Is there support for removing packages?" as asking whether there was a way to ask `straight.el` to remove a package, as opposed to asking whether it was intended behavior that deleting a package causes an error (the answer to the latter being no). Whoops :)

**Comment by raxod502** [comment]
It was a stupid bug, and I had a bit of extra time, so I just fixed it. It was pretty trivial, as expected.
