### ISSUE TITLE
Configurable Paths

### ISSUE THREAD

**Issue by nickgarber** [raxod502/straight.el#274]
I'd like to be able to specify the locations for the 

1. build dir, 
2. repo dir, and 
3. versions dir 

... ideally via the customize system.

**Comment by raxod502** [comment]
I was wondering when somebody would ask about this. I have no objection to it, except it will take a little bit of work to make it work correctly with the bootstrap system.

**Comment by raxod502** [comment]
Out of curiosity, what's your use case?

**Comment by nickgarber** [comment]
There are a few reasons this would make a difference for me, but the one that is front of mind is to 

... It'd support moving from my manual submodule-based config to use-package + straight.

In general it's a blend of aesthetics with data separation (to isolate personal info from my emacs.d). If it helps to illustrate, I'd set the repo-dir to where my submodules already live, the build-dir to the dir I already have setup as an `init.d` style directory, and the versions-dir to the directory where I store entirely personal info, like my custom-file, which I like to use extensively.

**Comment by raxod502** [comment]
Interesting. As I said, no objection here to supporting this directly. As a workaround, of course, you can simply symlink `~/.emacs.d/straight/repos`, `~/.emacs.d/straight/build`, etc. to your desired paths. I think that should work just as well.

**Comment by aqua36** [comment]
This would be useful for me as well. My use case is the following: I have my init.el and every other config file that is not a package in a separate directory plus a make file that creates an .emacs.d/init.el if it doesn't exist with a single line loading the init.el from my other dir. That way I keep only my custom dir under version control and it remains clean of anything emacs creates automatically. If you implemented this enhancement I would be able to set the versions dir to be inside my custom dir instead of messing with symlinks

**Comment by nickgarber** [comment]
I hacked-up a basically working (though messy) example here, https://github.com/nickgarber/straight.el/commit/b3f7838c8afc4acc1cb167cd32dbd349a6ae88ef

@raxod502 Any advice on how to clean this up or generalize it into something that'd make for a decent PR?

Biggest surprise in this process - I anecdotally found that Github's caching system can take up to 30 minutes to reflect updates. This was inspired great head-scratching until properly understood.

**Comment by raxod502** [comment]
Thanks. I'll take a look at this as soon as I have time (this may be a little while because I'm traveling to New York for the week). Why don't you go ahead and make it a pull request right away, so that the code review features work better? (We can always rebase it later to fix up the hacky parts.)

Also, yeah, I'm sorry on behalf of GitHub about the caching thing. That sucked to figure out when I was setting up the bootstrap installer the first time.

**Comment by raxod502** [comment]
Agreed. However, unfortunately I don't have spare time at the moment to work on code changes; I can only debug issues and review pull requests. If you'd like to get this through faster, perhaps you can adopt the pull request https://github.com/raxod502/straight.el/pull/300 :)

**Comment by nickgarber** [comment]
This request was completed to my satisfaction with #404. If there are any other part of this that are required by others please enter a new request. 

Thanks again for straight.el in general and for these changes in particular, @raxod502 !
