### ISSUE TITLE
Can't install `targets` package from Github

### ISSUE THREAD

**Issue by Townk** [raxod502/straight.el#275]
I'm trying to install a package that is not on MELPA and the installation is failing.

```elisp
(use-package targets
  :straight (:host github
             :repo "noctuid/targets.el")
  :after (general evil)
  :init
  (setq targets-user-text-objects '((paren "(" ")" pair
                                           :more-keys ("b" "9" "0")))
        targets-share-last-text-object t)

  :config
  (targets-define-to org-italic "/" nil quote
                     :hooks (org-mode-hook))
  (targets-define-to org-bold "*" nil quote
                     :hooks (org-mode-hook))
  (targets-define-to org-emphasis "_" nil quote
                     :hooks (org-mode-hook))
  (targets-define-to org-description ":" nil quote
                     :hooks (org-mode-hook))

  (general-define-key :keymaps 'global
                      :states '(visual operator)
                      "RET" #'targets-last-text-object)

  (targets-setup t))
```

This snippet doesn't install, and gives me the following error message:

> Debugger entered--Lisp error: (error "Package ‘targets-’ is unavailable")
>  signal(error ("Package ‘targets-’ is unavailable"))
>  error("Package `%s-%s' is unavailable" targets "")

Another thing I notice is that my setup is still puting packages under `~/.emacs.d/elpa/*` even though my bootstrap is this:

```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
(unless package--initialized (package-initialize t))

(with-eval-after-load 'gnutls
  (add-to-list 'gnutls-trustfiles "/usr/local/etc/libressl/cert.pem"))

(let ((bootstrap-file (concat user-emacs-directory "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 3))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
```

**Comment by Townk** [comment]
BTW, my Emacs version is `GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin17.5.0, NS appkit-1561.40 Version 10.13.4 (Build 17E199)) of 2018-04-10`

**Comment by raxod502** [comment]
`package.el` is not required in order to use `straight.el`; in fact, it is not recommended to use both `package.el` and `straight.el` at the same time. Unless you specifically want to do so, I would recommend removing the following lines from your configuration:

```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
(unless package--initialized (package-initialize t))
```

All packages from GNU ELPA, MELPA, and EmacsMirror can be installed via `straight.el`.

Once you make that change, I suspect that your error will go away, since it is generated by `package.el` and not `straight.el` (see [the relevant line of code in `package.el`](https://github.com/emacs-mirror/emacs/blob/b015fb0ce37235480af8d80bce8c2f9b7e6258eb/lisp/emacs-lisp/package.el#L1698-L1699)). Furthermore, you will not see any more use of `~/.emacs.d/elpa`, since that is also a result of `package.el` and not `straight.el`.

Just to be sure, I tested the bootstrap code you posted, minus the lines about `package.el`, plus the `(use-package targets ...)` configuration, and it worked fine with the latest versions of all packages.

Let me know if you have any other questions :)

**Comment by Townk** [comment]
You're correct. The problem I had originally (the one that made me add the package.el lines) was that use-package was erroring out about package.el not being initialized.

The core problem here is that I defined `use-package-always-ensure` as `t`, which makes use-package try to use package.el.

I might have missed this on your documentation, but if I didn't, is worth to mention that to integrate straight.el with use-package you should not set `use-package-always-ensure` to `t`.

**Comment by raxod502** [comment]
You are correct; I didn't mention anything about `use-package-always-ensure` in the documentation. Let me know what you think of https://github.com/raxod502/straight.el/commit/ccdb454ec7822098486b2f74c574e1f73e4a06bb?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8, and if there is any better way to make the information clear.
