### ISSUE TITLE
BBDB and straight seem to get along poorly

### ISSUE THREAD

**Issue by hartzell** [raxod502/straight.el#278]
I'm a newcomer to straight, by way of [sjrmanning's setup](https://github.com/sjrmanning/.emacs.d).

I've been merging and pruning and adjusting stuff to suit without any unsolvable problems.

I use a very old and creaky package called [BBDB](https://www.emacswiki.org/emacs/CategoryBbdb)  that I've been loading via a `(use-package ...` statement.

When I pulled it into my new config everything worked but I didn't appear to have anything in my address book.

After a bunch of poking and prodding I discovered that a brand new address book was being created in `~/.emacs.d/var/bbdb/bbdb.el` and the variable `bbdb-file` was being set to point to it.  If I explicitly `(setq bbdb-file "~/.bbdb.el") in the config section of my use-package statement then I'm back in business.

But, I'm curious if it's obvious what might be going on.

**Comment by raxod502** [comment]
The behavior is unrelated to `straight.el`. It's because [the configuration you linked uses the `no-littering` package](https://github.com/sjrmanning/.emacs.d/blob/161cafb8b8187ed35ada9ef2eb6be1c562d0ab00/modules/sm-path.el#L1-L6). This package resets paths for many different packages so that `~/.emacs.d` is more organized, [including `bbdb-file`](https://github.com/emacscollective/no-littering/blob/9bffebc0f4858a06ba374f1d48a7dffd3537b93e/no-littering.el#L256).

I recommend using `no-littering`, and moving your BBDB database to the new location. What kind of well-behaved Emacs package puts files outside of `~/.emacs.d`, anyway? :)

**Comment by hartzell** [comment]
> What kind of well-behaved Emacs package puts files outside of ~/.emacs.d, anyway? :)

Er, well, one that's old enough that it gets the senior discount...  🙊 

I *did* see that in the configs, but figured that bbdb was too obscure for it.  

*Thanks for the helping hand!*
