### ISSUE TITLE
Can't install elpa package jsonrpc

### ISSUE THREAD

**Issue by antifuchs** [raxod502/straight.el#293]
Hi again, I'm pretty much stuck on getting an update to eglot working (they [switched to declaring `jsonrpc` an elpa dependency](https://github.com/joaotavora/eglot/commit/07b235f159879932a9c232561bdb61d1a20b3e36), rather than vendoring the .el file). I'm getting `error: Could not find package jsonrpc in recipe repositories: (org-elpa melpa gnu-elpa emacsmirror)`; I updated my gnu-elpa checkout to the latest HEAD (`a4c994e966de87d618e39043364c53129e7e6f1d`), but the package can't be found. However, the package exists on the ELPA website here: [jsonrpc](https://elpa.gnu.org/packages/jsonrpc.html).

Does ELPA include packages that aren't in git? How would I install those? Is here the right place to report this, or should I go to the ELPA maintainers?

**Comment by raxod502** [comment]
Oh, god. It looks like this is going to be _really_ horrifying. So here's the problem:

* Yes, ELPA includes packages that aren't in Git—there's a list in the `externals-list` file in the GNU ELPA Git repository.
* The entry for `jsonrpc` (which was added only on June 30) is:

  ```elisp
  ("jsonrpc" :core "lisp/jsonrpc.el")
  ```

* Which means that `jsonrpc` is "officially" (and only) located in Emacs core, i.e. `lisp/jsonrpc.el` in the source repository.
* But since it was added on June 30, there is no released version of Emacs that includes this file.

So this leaves us with the question of how on earth we are supposed to obtain this file. `straight.el` *could* retrieve it from the official location, i.e. the Emacs source repository (in fact, if you're desperate, you can just do that yourself). For example:

    (straight-register-package
     '(jsonrpc :repo "https://git.savannah.gnu.org/git/emacs.git"
               :files ("lisp/jsonrpc.el")))
               
But the Emacs source repository is like 1GB and takes forever to clone, so I don't really consider this to be a good option.

Another dumb idea is to just make a Git repository yourself which hosts the single file `jsonrpc.el`, and load it from there. It doesn't look like the EmacsMirror hosts `:core` ELPA packages, unfortunately, so we can't expect this package to show up there either.

Maybe I can just make a GitHub organization for `straight.el` and write a script that takes my local clone of GNU ELPA and mirrors all the packages there (including the `externals-list` ones, using my local clone of the Emacs source repository) as separate repositories. I've been having trouble with GNU ELPA's convoluted build process for ages; in fact, support was dropped and only recently re-added. This would solve all of those problems, and make it possible for people to use GNU ELPA in a sane manner. (It would also solve <https://github.com/raxod502/straight.el/issues/240>, which is quite important.)

Any thoughts?

> Is here the right place to report this, or should I go to the ELPA maintainers?

:'(

Unfortunately, here is the right place to report this, because all the ELPA maintainers care about is whether their weird build system works with `package.el`.

**Comment by raxod502** [comment]
Congrats, your issue finally pushed me off the cliff of sanity and I now maintain a [full mirror of GNU ELPA on GitHub](https://github.com/emacs-straight). You can tell `straight.el` to use it by customizing the user option `straight-recipes-gnu-elpa-use-mirror`. This should allow you to install jsonrpc as desired.

;)

**Comment by raxod502** [comment]
See also #240.

**Comment by antifuchs** [comment]
Hahaha, thanks for the quick fix! I'll customize that setting now (:

**Comment by alanz** [comment]
I find that customizing `straight-recipes-gnu-elpa-use-mirror` to `t` has no effect, I presume due to the timing of the bootstrap process.

If I edit it directly in `straight.el` then it works as expected.

**Comment by raxod502** [comment]
You must customize the variable *before* the `straight.el` bootstrap. I didn't realize that this fact was missing from the documentation, and I've now added it.

**Comment by alanz** [comment]
So for the avoidance of my doubt, the customisation should be done by something like

```elisp
(setq straight-recipes-gnu-elpa-use-mirror t)
```
before the bootstrap code.

Because the emacs customise stuff lives at the end of the `~/.emacs` file, with the following comment

```elisp
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
``` 
Or should it be moved to the top of the file? Which means it may not have loaded the stuff it refers to?

Sorry, I am not an elisp expert.
