### ISSUE TITLE
Possible to use with submodules instead of a freeze file?

### ISSUE THREAD

**Issue by mgsloan** [raxod502/straight.el#301]
It is true that submodules have some "sharp corners".  However, once you've used them enough, you know what to expect, and they work pretty well.  In particular one reason I think I'd prefer them over the freeze file is that when making commits to your emacs config repo, `git status` makes it clear that there are changes which aren't included.  If I need to remember to generate the freeze file, then this means that it could be quite easy to forget to update.

Not being reminded to update the freeze file could harm the expected reproducibility. Every commit that you forgot to update the freeze file, when it differed, would not be the same configuration as you were using.  Perhaps some variety of git commit hook could be used to catch that the freeze file has not been updated?  That would cover the main advantage of submodules.

Overall I like how easy it was to switch from using `(setq use-package-always-ensure t)` to `(setq straight-use-package-by-default t)`.  Really nice!  Far more straightforward to setup than borg, which I was also looking into due to my preference for submodules.

**Comment by raxod502** [comment]
You can easily use submodules if you simply make `~/.emacs.d/straight/repos` into a Git repository, and register its subdirectories as submodules. I believe you could also make `~/.emacs.d/straight/repos` into a symlink pointing at a directory elsewhere. (See also #274 about letting you set this path directly instead of using a symlink.)

If you would like to be able to have unused repositories that aren't part of your configuration (i.e. you don't want to delete them to get them to stop being untracked files), then it is a little more difficult. One approach would be to use `.gitignore`. Alternatively, you can specify explicit recipes for each of your packages with `:local-repo` values pointing at submodules in some Git repository elsewhere. I'm sure one could come up with some way to automate this, although I'm not sure exactly what it would look like. The only disadvantage to the `:local-repo` solution is that live modification detection and file-watcher integration doesn't support `:local-repo` values outside of `~/.emacs.d/straight/repos`, so you would have to stick with the default of eager modification detection. You may be able to work around this problem, however, by putting all of the local repositories that are a part of your configuration into a subdirectory of `~/.emacs.d/straight/repos`, and only making that subdirectory a Git repository (or symlinking it into a Git repository). Note that `straight.el` doesn't have to manage your Git repositories at all, if you don't want it to. Thus, you have a lot of flexibility here.

It would also of course not be difficult to automatically freeze the `straight.el` lockfile on each commit. You would just need to do something like

```
emacs -nw --eval "(straight-freeze-versions)"
```

in the commit hook. A little slow and also awkward if you are rebasing, but it does what you want I think.

**Comment by mgsloan** [comment]
Awesome, thanks for the detailed answer @raxod502 , much appreciated.

I'm not very experienced with elisp beyond copy-modifying configs, but I copy-modified some straight.el functions to put together a utility to automate transforming the repos into submodules:

```elisp
(defun straight-add-submodule (package)
  (interactive (list (straight--select-package "Add submodule" nil 'installed)
                     current-prefix-arg))
  (let ((recipe (gethash package straight--recipe-cache)))
    (straight-vc-add-submodule recipe)))

(defun straight-add-submodule-all (predicate)
  (interactive "P")
  (straight--map-existing-repos-interactively
   (lambda (package)
     (straight-add-submodule package))
   predicate))

(defun straight-vc-add-submodule (recipe)
  (straight--with-plist recipe
      (local-repo type)
    (when local-repo
      (let ((straight--default-directory (straight--repos-dir)))
        (straight-vc 'add-submodule type recipe)))))

(cl-defun straight-vc-git-add-submodule (recipe)
  (straight--with-plist recipe
      (local-repo repo host)
    (let ((url (straight-vc-git--encode-url repo host)))
      (unless (straight--check-call "git" "ls-files" "--error-unmatch" local-repo)
        (straight--get-call "git" "submodule" "add" url local-repo)))))
```

It seems to work on my config with about 30 packages!  Should work in general.  Please let me know if I should add comments and open a PR.  No worries if you don't think it should be added to the main repo, I can certainly understand not wanting to deal with adding full support for the submodule workflow.

> in the commit hook. A little slow and also awkward if you are rebasing, but it does what you want I think.

I guess for this to work properly you'd probably need to thaw.  Indeed, a bit awkward for the rebase case, and this is one of the cases where submodules are awkward too.

**Comment by raxod502** [comment]
> Please let me know if I should add comments and open a PR.

You could add it to `straight-x.el`, if you want. For it to be added to the main package, I think the implications need to be thought through more.

I guess this issue is more or less solved, then. Let me know if you have further concerns.

**Comment by mgsloan** [comment]
Yep, this is resolved, thanks!

I've put down a todo note to open a PR for putting it in `straight-x.el`.  Not certain if / when I will get around to it.

Since I am only just starting to use this, I can't think through the implications with any accuracy.  It does seem like full support of this mode would probably involve automatically doing `straight-add-submodule` upon fresh clone.  It also might involve commands to stage all the changes to the submodules.  Quite fine with just using magit for all that though.

**Comment by mgsloan** [comment]
FWIW, I didn't realize how easy it is to add submodules with magit (just stage the dir).  So, I don't think it's very helpful to add the utilities I wrote above
