### ISSUE TITLE
"error: Could not find package mmm-mode in recipe repositories: (org-elpa melpa gnu-elpa emacsmirror)"

### ISSUE THREAD

**Issue by mgsloan** [raxod502/straight.el#305]
I don't think this is an issue with straight.el , but instead my own understanding of emacs packages / recipes.

Repro: I'm just using essentially `(use-package mmm-mode)`, and have manually checked out https://github.com/purcell/mmm-mode into `straight/repos`.  Technically I added it as a submodule, but that's just my idiosyncratic workflow :)

Result:

```
Warning (initialization): An error occurred while loading ‘/home/mgsloan/.emacs.d/init.el’:

error: Could not find package mmm-mode in recipe repositories: (org-elpa melpa gnu-elpa emacsmirror)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

The reason this is puzzling is that it is in elpa - https://elpa.gnu.org/packages/mmm-mode.html - but indeed I do not see anything for it in `straight/repos/elpa/packages`.

What can I do to make it accept `mmm-mode`?  Thanks!

**Comment by raxod502** [comment]
You have two options.

Option 1 is to use `mmm-mode` from the upstream repository. In this case you should specify a recipe for it so that `straight.el` knows to clone it from there.

```elisp
(straight-use-package '(mmm-mode :host github :repo "purcell/mmm-mode"))
```

Option 2 is to use `mmm-mode` from GNU ELPA. Since GNU ELPA is stupid and broken, this doesn't work out of the box. I suggest using the GNU ELPA mirror that I created to work around this problem:

```elisp
;; do this before bootstrapping straight.el
(setq straight-recipes-gnu-elpa-use-mirror t)

;; then later
(straight-use-package 'mmm-mode)
```

You may wonder some things.

Firstly, why can't `straight.el` figure out how to pull `mmm-mode` from the upstream repository? This is basically because GNU ELPA uses a totally broken package management model, as previously mentioned. The "official" version of `mmm-mode` that is served from the GNU ELPA package archive is not taken from the upstream URL, but rather from a separate branch of the GNU ELPA repository itself that may or may not differ from the upstream. If you just fetch from the upstream, then this breaks certain packages like AUCTeX that rely on these additional GNU-ELPA-specific changes in order to work at all. And I have no interest in supporting some bizarre hackery based on `git-worktree` that would allow you to use multiple branches of GNU ELPA at once. Instead, if you want to use these packages, you should just use the GNU ELPA mirror, as previously mentioned. I intend to make this happen by default in the future. If this annoys you, then you should ask the MELPA folks to add `mmm-mode` to their (not totally broken) package repository, so that it can be installed in a sane way.

Secondly, why is specifying a recipe necessary? Well, you always must either specify a recipe, or let one be looked up. And if you don't use the GNU ELPA mirror, then GNU ELPA won't provide a recipe for `mmm-mode`.

If you really don't care about `straight.el`'s automated repository management features, you could just use this instead:

```elisp
(straight-use-package '(mmm-mode :local-repo "mmm-mode.el"))
```

**Comment by mgsloan** [comment]
Great, thanks for the detailed explanation!  Much appreciated

The `(straight-use-package '(mmm-mode :host github :repo "purcell/mmm-mode"))` approach worked, but the elpa mirror didn't.  Glad to have it resolved either way, though.

**Comment by raxod502** [comment]
What didn't work about using the GNU ELPA mirror? It seems to work for me.

**Comment by mgsloan** [comment]
Curious!  I got the same output as describe in my original description, using something analogous to

```elisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
(setq straight-recipes-gnu-elpa-use-mirror t)

(straight-use-package 'mmm-mode)
(use-package mmm-mode)
```

Whereas this works fine:

```elisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(straight-use-package '(mmm-mode :host github :repo "purcell/mmm-mode"))
(use-package mmm-mode)
```

**Comment by raxod502** [comment]
You need to set `straight-recipes-gnu-elpa-use-mirror` _before_ you bootstrap `straight.el`; otherwise, the change will not take effect.

**Comment by mgsloan** [comment]
Ohh yes that's the missing bit I'll bet.  Thanks!
