### ISSUE TITLE
 OpenBSD 6.4: "find: -newermt: unknown option"

### ISSUE THREAD

**Issue by sideproject** [raxod502/straight.el#325]
straight.el commit: 3162136026660f3c9ab9e96a3a81b2a99f2612c0
emacs version: GNU Emacs 26.1 (build 1, x86_64-unknown-openbsd) of 2018-10-12

I encounter this error when loading emacs on OpenBSD 6.4: 
```
error: Command failed: find . -name .git -prune -o -newermt 2018-11-10\ 20\:33\:55-0500 -print:
find: -newermt: unknown option
```

It appears that the version of find used on OpenBSD doesn't accept the -newermt parameter.  I was able to get around the issue by forcing the find flavor to be BusyBox with the patch below:

```
@ -1043,9 +1043,22 @@ Return a symbol."
         ;; Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]
         ;; [...]
         ;; exit code 1
+
+        ;; == OpenBSD 6.4
+        ;;
+        ;; find: unknown option -- -
+        ;; usage: find [-dHhLXx] [-f path] path ... [expression]
+        ;; [...]
+        ;; exit code 1
+
         (call-process "find" nil '(t t) nil "--version")
-        (goto-char (point-min))
-        (if (search-forward "BusyBox" nil 'noerror)
+        (if (or
+              (progn
+                (goto-char (point-min))
+                (search-forward "BusyBox" nil 'noerror))
+              (progn
+                (goto-char (point-min))
+                (search-forward "unknown option" nil 'noerror)))
             'busybox
           'gnu/bsd))
     ;; Just an educated guess.
@@ -1061,7 +1074,8 @@ are constructed. The `gnu/bsd' value is compatible with:
```

I'd be happy to submit a pull request if this is something you'd be willing to accept or discuss.

**Comment by raxod502** [comment]
That would indeed be one way of solving the problem. However, on looking back at my code, it seems completely stupid, because if we want to check if `-newermt` is supported, then we can just run a `find(1)` command that uses `-newermt` and check if it succeeds. (The original reason for doing it the way I did it, I think, was because BusyBox didn't support time zones in `touch -d`. But there is really no reason to use time zones at all, as far as I can tell, so I just dropped that entire part of the code, making everything much simpler.)

I think the commit I just pushed should fix your issue; please let me know if it doesn't.
