### ISSUE TITLE
Profiling init configs built with straight.el

### ISSUE THREAD

**Issue by matthew-piziak** [raxod502/straight.el#332]
`straight.el` [appears to be incompatible with ESUP](https://github.com/jschaf/esup/issues/54#issuecomment-443511193), the Emacs Start-Up Profiler. What is the right way to profile dotemacsen that are fixtured with `straight.el`?

**Comment by raxod502** [comment]
Works for me, with the following code in `init.el` and running `M-x esup` after initial installation from an otherwise empty `~/.emacs.d`:

```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'esup)
```

This is running command-line Emacs 26.1 from Homebrew `--with-cocoa --with-modules` on OS X 10.11.6.

Could you provide some steps to reproduce the problem? FWIW, [my own Emacs configuration uses ESUP](https://github.com/raxod502/radian/blob/c4246176155873d3937ff997965279048dabbc01/emacs/radian.el#L4423-L4476).

**Comment by wedens** [comment]
Works for me in emacs 27.0.50 on GNU/Linux.

I had this problem before and I think (but I'm not sure it is the reason) it disappeared after upgrading emacs from 26.1 to 27.0.50.

**Comment by jkp** [comment]
I had the same issue here - I tried updating emacs as stated above but it didn't help.  In the end I noticed a that some error messages referenced my `~/.recentf` file so I disabled that module and deleted the file and `esup` started working. YMMV.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
