### ISSUE TITLE
Strange issues with "customize"

### ISSUE THREAD

**Issue by Fuco1** [raxod502/straight.el#351]
I've switched some packages to be managed by straight, for example `elfeed`.  I have some customization for the paths where it stores database etc. set through the Emacs customize interface.

I first load the custom file and then invoke `use-package`.  However, elfeed after being loaded, used its default settings.

Did anyone have some problems with customize before?  I'm not sure if it's linked to the package.el system somehow.  I have about 2000 settings set through that so it's a big concern... if it doesn't work it can probably break my persistent state in subtle ways.

Note that I am moving away from it since it's a terrible system when it comes to synchronizing the settings, but I still quite liked the UX/discoverability.  However it must work in the meantime until I fully transition.

**Comment by raxod502** [comment]
I don't know why you would want to set your settings _before_ making the package available, but then I don't use Customize. Could you provide a minimal example that shows this behavior?

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
