### ISSUE TITLE
EmacsMirror takes a long time to clone

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#356]
One bad piece of UX of `straight.el` currently is that as soon as you hit either a built-in package or a package on EmacsMirror, then `straight.el` tries to clone EmacsMirror, and this takes _forever_—even on a fast network connection. I think we can fix this problem.

The easiest way, IMO, would be to extend [gnu-elpa-mirror](https://github.com/raxod502/gnu-elpa-mirror) to maintain a mirror of [the epkgs repository](https://github.com/emacsmirror/epkgs) with the SQLite database file removed. This would effectively solve the problem because the resulting repository would be tiny and fast to clone.

**Comment by tarsius** [comment]
Since https://github.com/emacsmirror/epkgs/commit/35d6f35d9bec9e0ca6f92cf459256c3577d08123 the epkgs repository no longer tracks a sqlite database. Instead of the binary database file `epkgs.sqlite` it tracks a text file `epkgs.sql`, from which the former is created on the client-side.

The epkgs repository does not contain any history from before this change. That history is preserved in a separate repository [epkgs-v4](https://github.com/emacsmirror/epkgs-v4).

```lisp
time git clone git@github.com:emacsmirror/epkgs.git
Cloning into 'epkgs'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 2876 (delta 61), reused 76 (delta 58), pack-reused 2793
Receiving objects: 100% (2876/2876), 15.90 MiB | 9.17 MiB/s, done.
Resolving deltas: 100% (2192/2192), done.

real    0m14.455s
user    0m35.813s
sys     0m0.387s
```

**Comment by raxod502** [comment]
Ah, lovely! We can remove this piece of infrastructure, then: https://github.com/raxod502/straight.el/issues/700
