### ISSUE TITLE
Don't clone org when built-in version will work

### ISSUE THREAD

**Issue by CeleritasCelery** [raxod502/straight.el#361]
`ox-hugo` lists org `9.0` as a dependency. Emacs 26.1 ships with org `9.1.9`. However when I try and use straight to install `ox-hugo` it attempts to clone org as an external package (which fails because of an SSL certificate problem, but that is irrelevant). If the built-in version of org meets the package requirements, There is no need to clone the external package (and some users, including myself, can't get it.)

**Comment by raxod502** [comment]
You may not realize this, but `straight.el` completely ignores all version numbering and does not include a dependency resolver. The reasoning for this is that such features would add extraordinary complexity without really improving user experience in all but the most remote of circumstances.

The fact that it always tries to install all packages, rather than relying on the ones shipped with Emacs, is an explicit design choice. The reasoning for this is that users should receive the most recent versions of packages by default, and versions shipped with Emacs are always outdated.

If you want to use the built-in version:

```elisp
(straight-use-package '(org :type built-in))
```

**Comment by CeleritasCelery** [comment]
Thanks, that worked. I understand your reasoning for not want to add a version resolver.

**Comment by raxod502** [comment]
Great :)

See also #328 for documenting the fact that this feature exists.
