### ISSUE TITLE
straight.el breaks `run-with-idle-timer`?

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/straight.el#369]
It has been a long story... see this: <https://github.com/jwiegley/use-package/issues/758>

Anyway, here's the thing: I would like to defer loading `hydra` by several seconds using `run-with-idle-timer`, and do some lazy configure thing using `with-eval-after-load`. This works nice:

``` emacs-lisp
(straight-use-package 'hydra)
(run-with-idle-timer 2 nil #'require 'hydra nil t)
(with-eval-after-load 'hydra
  (message "hydra loaded."))
```

`hydra loaded.` shows up after a while from emacs startup. But this doesn't work:

``` emacs-lisp
(straight-use-package 'hydra)
(run-with-idle-timer 2 nil #'require 'hydra nil t)
(with-eval-after-load 'hydra
  (message "hydra loaded.")
  (defhydra my-hydra (:hint nil) "_s_wiper" ("s" swiper)))
```

`hydra loaded.` shows immediately after startup. If I using `(add-to-list 'load-path "~/.emacs.d/straight/build/hydra")` instead of `(straight-use-package 'hydra)`, It'll work again.

If using `use-package` like this:
``` emacs-lisp
(use-package hydra
  :defer 2
  :config
  (message "hydra loaded.")
  (defhydra my-hydra (:hint nil) "_s_wiper" ("s" swiper)))
```

 calling `defhydra` in the `:config` block will also cancel `:defer 2`.

Do you guys have any idea why this happenes?

**Comment by raxod502** [comment]
Eager macroexpansion triggering the autoload of `defhydra`. If you want to avoid it, either byte-compile your init-file or wrap the macro in a runtime `eval` form: `(eval '(defhydra ...))`. This doesn't have anything to do with `straight.el`; you would see the same behavior with `package.el`. (Your "plain Elisp" example in [jwiegley/use-package#758](https://github.com/jwiegley/use-package/issues/758) works because you didn't load the autoloads file.) For what it's worth, the strange behavior here results from the behavior of `with-eval-after-load` (i.e. that it allows macroexpansion within its body before the feature is loaded), not from `run-with-idle-timer`. See also [my configuration](https://github.com/raxod502/radian/blob/bf23a07418b3d72a300b21dcdf9cb521423d9681/emacs/radian.el#L30-L49).

**Comment by AmaiKinono** [comment]
@raxod502 Ah, I see. Thanks for your reply! Sorry that I am an elisp noob :joy:. Your `radian-protect-macros` macro is really a neat helper, I'll definitely have that in my config :smile:.

**Comment by raxod502** [comment]
> That macro happenes to be an autoload thing,

Yes.

> so this causes the autoload file to be loaded

No, the autoloads file was already loaded; otherwise the macro wouldn't be defined as an autoload.

> and some of its subform uses something in the package itself

No, the package is loaded directly as a consequence of the autoload being triggered.

> can I use `(eval-when-compile '(defhydra ...))` rather than `eval`?

I don't think so. My understanding is that if you don't byte-compile, then the form is evaluated during macroexpansion, i.e. this doesn't solve the problem. See the source code of `eval-when-compile`: it just uses `eval` at macroexpansion time.

> It seems work for me.

I couldn't say why. If you find out, let me know.

**Comment by AmaiKinono** [comment]
@raxod502 Thanks! That made it clear for me. As for `eval-when-compile`, yes you are right, it doesn't work as I thought, somewhat I just got it wrong.

**Comment by raxod502** [comment]
Great! I'll close this then.
