### ISSUE TITLE
Setting "--depth=1" doesn't work when clone magit 

### ISSUE THREAD

**Issue by lczch** [raxod502/straight.el#378]
I have set `(setq straight-vc-git-default-clone-depth 1)` and use below code to clone magit:
````
(straight-use-package
 '(magit :type git :host github :repo "magit/magit"
                      :no-build t
                      :fork (:host github
                                   :repo "lczch/magit")
                      ))
````
But it keeps to clone the whole history of magit (with long time). 

It seems the `depth` parameter doesn't take effect when cloning magit.
But when I clone other pacakages(e.g. `with-editor` or `transient`), the `depth` works fine.

My environment consists of emacs 26.1, msys2, Win 8. 
And I also use the latest `develop` branch of straight.

Thanks !

**Comment by raxod502** [comment]
cc @shwaka

**Comment by lczch** [comment]
I have found the latency is caused by `git fetch fork`, according to the log of `straight` as below:
````
$ cd c\:/msys64/home/lzh/rice-wine/straight/repos/
$ git clone --origin origin --no-checkout git\@github.com\:magit/magit.git c\:/msys64/home/lzh/rice-wine/straight/repos/magit/ --depth 1 --branch master

Cloning into 'c:/msys64/home/lzh/rice-wine/straight/repos/magit'...

[Return code: 0]

$ cd c\:/msys64/home/lzh/rice-wine/straight/repos/magit/
$ git remote add fork git\@github.com\:lczch/magit.git

[Return code: 0]

$ cd c\:/msys64/home/lzh/rice-wine/straight/repos/magit/
$ git fetch fork
...
````
`git fork` will clone the whole history of magit from my fork. 
Thus actually we also need transfer `--depth` to `git fetch fork`?

**Comment by lczch** [comment]
And I am also curious about why `straight` choose to clone `origin`(in other world, `upstream`) at the very beginning. 
In my opinion, however, a `fork` means user will always use their own fork and only need `origin` when they want to get the newest update from the origin. 
Is it necessary to fork/clone the origin repo at the very beginning?
@raxod502 

Thanks!

**Comment by raxod502** [comment]
Both remotes need to be created, and Git requires you to clone from one of them to get started. (Or maybe we could `git init` an empty directory and then add remotes and fetch manually?) I guess you could clone first from the fork, and then later add the upstream, instead of the other way around. Clearly the interaction of this mechanism and `--depth` needs to be better-thought-out.

**Comment by progfolio** [comment]
According to this test case, it looks like everything is working as expected:


<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "magit-depth.straight"
  :preserve t
  :post-bootstrap 
  (setq straight-vc-git-default-clone-depth 1)
  (straight-use-package
   '(magit :build nil :fork "progfolio/magit"))
  (let
      ((default-directory
         (straight--repos-dir "magit")))
    (message "magit repo depth: %s"
             (straight--process-output "git" "rev-list" "HEAD" "--count"))))
```
</details>

- Test run at: `2021-06-02 12:05:33`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 7ca94a7 2021-06-01`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-05-25`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 7ca94a7 2021-06-01
Cloning magit...
Cloning magit...done

magit repo depth: 1
Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 54457e29 2021-06-02
"gnu-elpa-mirror"         n/a                  master 6417888 2021-05-29
"el-get"                  melpa                master d76ac84a 2021-04-28
"emacsmirror-mirror"      n/a                  master a3cf645 2021-05-29
"straight"                n/a                  develop 7ca94a7 2021-06-01
"magit"                   melpa                master 4a8646a 2021-05-31


```
</details>

I'll close this since there hasn't been any development on this in quite some time, but feel free to comment if we need to reopen.
