### ISSUE TITLE
clean repos directory?

### ISSUE THREAD

**Issue by mfiano** [raxod502/straight.el#388]
Is there any functionality to clean up the `repos` directory of any sources not in my version file? I noticed I had a lot of package repos downloaded that I no longer use. I am not talking about the build directory. Thanks!

**Comment by raxod502** [comment]
See https://github.com/raxod502/straight.el/issues/49.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
