### ISSUE TITLE
How to define multiple packages out of a single repository?

### ISSUE THREAD

**Issue by rgrinberg** [raxod502/straight.el#408]
Some repositories define multiple packages, for example agda defines multiple packages: [agda2, agda2-mode](https://github.com/agda/agda/tree/master/src/data/emacs-mode) etc. What is the correct way to write a recipe for such packages?

**Comment by raxod502** [comment]
Check out the recipes for `swiper`, `ivy`, `counsel`.

```
(swiper :type git :flavor melpa :files ("swiper.el" "swiper-pkg.el") :host github :repo "abo-abo/swiper")
(ivy :type git :flavor melpa :files (:defaults (:exclude "swiper.el" "counsel.el" "ivy-hydra.el") "doc/ivy-help.org" "ivy-pkg.el") :host github :repo "abo-abo/swiper")
(counsel :type git :flavor melpa :files ("counsel.el" "counsel-pkg.el") :host github :repo "abo-abo/swiper")
```

**Comment by rgrinberg** [comment]
Thanks, I've successfully written my recipe. Perhaps it would make sense to define multiple recipes at once this way? It's quite a common situation.

**Comment by raxod502** [comment]
> It's quite a common situation.

I'd kinda like to think that it would be better to encourage package authors not to maintain more than one package in a single repository. It adds needless complexity. Besides, most packages like this are already popular enough for their recipes to be in MELPA or Emacsmirror, so the problem is a bit self-correcting.

It's rather like build steps: yeah, `straight.el` can support them (#72), but Emacs already has great facilities for running shell commands interactively; wouldn't it be a better user experience for packages requiring compilation steps to implement them using the full power of the Emacs interface? Then they could decide for themselves exactly when a recompile is needed, leading to improved user experience.

**Comment by rgrinberg** [comment]
> I'd kinda like to think that it would be better to encourage package authors not to maintain more than one package in a single repository. It adds needless complexity

I disagree here. It adds needless complexity for *package managers* but it simplifies quite a lot for maintainers. It's much easier to maintain a single set of packages in one repository without providing backwards compatibility guarantees for partial upgrades. In my opinion, `straight.el` should strive to support this workflow as well as possible as it is quite important.

**Comment by raxod502** [comment]
> partial upgrades

Okay, fair enough, I didn't think about that use case.

I still think it's not that big of a priority since any important packages should really be added to a recipe repository so that everyone doesn't have to redo the work of defining the recipes, but I'd be happy to merge a pull request implementing the feature you describe.
