### ISSUE TITLE
Replacement for package.el's options

### ISSUE THREAD

**Issue by sorenbug** [raxod502/straight.el#419]
Taking this snippet:
```elisp
;; Enable scala-mode and sbt-mode
(use-package scala-mode
  :mode "\\.s\\(cala\\|bt\\)$")

(use-package sbt-mode
  :commands sbt-start sbt-command
  :config
  ;; WORKAROUND: https://github.com/ensime/emacs-sbt-mode/issues/31
  ;; allows using SPACE when in the minibuffer
  (substitute-key-definition
   'minibuffer-complete-word
   'self-insert-command
   minibuffer-local-completion-map))

;; Enable nice rendering of diagnostics like compile errors.
(use-package flycheck
  :init (global-flycheck-mode))

(use-package lsp-mode
  ;; Optional - enable lsp-mode automatically in scala files
  :hook (scala-mode . lsp)
  :config (setq lsp-prefer-flymake nil))

(use-package lsp-ui)

;; Add company-lsp backend for metals
(use-package company-lsp)
```
from [Metals' Emacs install instructions](https://scalameta.org/metals/docs/editors/emacs.html#installation), I assume there are two options:
- Use `use-package` with `:straight t`
- Use `straight-use-package` and rewrite what `:config`/`:hook`/`:init` do

I'd like to receive guidance on how to accomplish the second, or a general rule on what those `use-package` options do so I can rewrite it from there.

**Comment by raxod502** [comment]
I am confused about why you don't want to use `use-package`. It is a better solution.

That said, if you want to migrate `use-package` code back to vanilla Elisp, I'm afraid this issue tracker is not really the right way to get support for that, since it is not really a `straight.el` question, but a `use-package` one.

Just to be clear, all this does:

```elisp
(use-package foo
  :straight t
  ... some other stuff ...)
```

is expand to this:

```elisp
(straight-use-package 'foo)
(use-package foo
  ... some other stuff ...)
```

**Comment by sorenbug** [comment]
Ah ok. I thought it did something different and that's why I didn't want to use `use-package` in my situation.

**Comment by raxod502** [comment]
Great, glad I could answer your question. If you'd like to explore how `use-package` works more, I would suggest using the [macrostep](https://github.com/joddie/macrostep) package.

**Comment by minikN** [comment]
@raxod502 

I have a question regarding this issue. Given that 
 
> Just to be clear, all this does:
> 
> ```emacs-lisp
> (use-package foo
>   :straight t
>   ... some other stuff ...)
> ```
> 
> is expand to this:
> 
> ```emacs-lisp
> (straight-use-package 'foo)
> (use-package foo
>   ... some other stuff ...)
> ```

This is an issue if using `use-package` with a package name that `use-package` is not able to find.

See the following:

```
(use-package emacs-monokai-pro-theme
  :straight (:host github :repo "minikN/emacs-monokai-pro-theme")
  :init (load-theme 'monokai-pro t))
```
This snippet is working. It installs my [fork](https://github.com/minikN/emacs-monokai-pro-theme) of belak's [monokai-pro-theme](http://melpa.org/#/monokai-pro-theme).
However, after it's done, I'm getting the following error:

```
Error (use-package): Cannot load emacs-monokai-pro-theme
```

This happens because `use-package` can't find `emacs-monokai-pro-theme`, cause it's actually called `monokai-pro-theme`. Maybe I'm misunderstanding this, but wasn't the purpose of `straight-use-package` to give the ability to provide github repos as sources?

This is working as well:
```
(straight-use-package
 '(emacs-monokai-pro-theme :type git :host github :repo "minikN/emacs-monokai-pro-theme"))
```

However then I'm not able to use `use-package`'s `:init` option, right?

So I get that renaming the package to `monokai-pro-theme` in the first snippet solved the issue. But I don't understand what I would do if I try to feed `(use-package <name> :straight (...))` a package name that doesn't exist on any repo.

Thanks.

**Comment by raxod502** [comment]
`use-package` *does not take a package name*. It takes a _feature_ name. The feature name can be different from the package name. In your case, the package name is `emacs-monokai-pro-theme` while the feature name is `monokai-pro-theme`.

So just write:

```elisp
(use-package monokai-pro-theme
  :straight (emacs-monokai-pro-theme :host github :repo "minikN/emacs-monokai-pro-theme")
  :init (load-theme 'monokai-pro t))
```

Or, with recently added [recipe inheritance](https://github.com/raxod502/straight.el/pull/427), just

```elisp
(use-package monokai-pro-theme
  :straight "minikN/emacs-monokai-pro-theme")
```
