### ISSUE TITLE
Emacs crashes if there are unbalanced parentheses

### ISSUE THREAD

**Issue by brotzeit** [raxod502/straight.el#434]
I noticed this when I tried to rebuild a package with `(straight-rebuild-package mypackage)`.

This is the only issue I had so far. Thanks for the great package!

**Comment by raxod502** [comment]
Please give instructions for how to reproduce the behavior _starting from an empty `~/.emacs.d`_. Unfortunately, I simply don't have enough time to check out your bug report unless it has clear instructions for this. To do this, start with an empty `~/.emacs.d/init.el`, add the bootstrap snippet, and then add any additional code from your init-file that's needed to set up the buggy behavior. Then include a list of steps to follow (commands to run, files to modify, whatever) after Emacs startup.

If you do this and can't reproduce the problem, it must be something particular to your environment or configuration. In this case, you'll have to bisect in order to figure out what is causing the problem. I won't be able to debug a problem that only happens on your computer!

**Comment by brotzeit** [comment]
My bad, sorry. Checkout emacs master and `(setq debug-on-error t)`. It seems this was introduced somewhere around "56a90c4234 * Output progress messages when scraping autoloads during bootstrap".

This fixes it for me:

```diff
modified   straight.el
@@ -4121,7 +4121,8 @@ modifies the build folder, not the original repository."
         ;; (for example, adding to `recentf') when visiting the
         ;; autoload file.
         (let ((find-file-hook nil)
-              (write-file-functions nil))
+              (write-file-functions nil)
+              (debug-on-error nil))
           ;; Actually generate the autoload file.
           (update-directory-autoloads
            (straight--build-dir package)))
```

**Comment by raxod502** [comment]
Is this the error you get?

![image](https://user-images.githubusercontent.com/6559064/68602908-12f88280-045c-11ea-9899-8e70b3e9b478.png)

**Comment by brotzeit** [comment]
When I turn off `debug-on-error`, yes. And with older emacs I always get this error even with `debug-on-error` set to t.

**Comment by raxod502** [comment]
Okay, I added the patch you suggested. Let me know if there is anything else that should be changed for `straight.el`.

**Comment by raxod502** [comment]
To reproduce, add a trailing left parenthesis to the Elisp code of some package that is going to be built by `straight.el`.
