### ISSUE TITLE
Concatenate package code that is loaded during startup

### ISSUE THREAD

**Issue by piotr-yuxuan** [raxod502/straight.el#438]
Hello, thanks for this amazing tool. It's really changed the way I setup my Emacs!

Here is the actual time needed to evaluate my `init.el`:

``` zsh
$ time /Applications/Emacs.app/Contents/MacOS/Emacs --eval '(kill-emacs)'
/Applications/Emacs.app/Contents/MacOS/Emacs --eval '(kill-emacs)'  1.30s user 0.63s system 69% cpu 2.779 total
```

I find it slow. I don't imply it's necessarily because of `straight.el`, however I wonder whether the latter could gather all package code loaded from `init.el`, put it in a big file, and compile it. Would it be possible? wouldn't it be super fast?

**Comment by raxod502** [comment]
My Emacs loads in 0.33s with 150 packages, so such times are achievable in certain configurations and with certain hardware under `straight.el`. If you haven't set up the filesystem watcher, then you should do so in order to improve startup time, especially if you do not have an SSD.

What you suggest would be very difficult due to the dynamic nature of Emacs configuration, but not impossible. In particular, it would likely require the introduction of a new package because cooperation would be required between all parts of the initialization process, not just `straight.el`. I would encourage anyone who thinks this is a promising approach to take a look and report findings.

It is worth noting that a similar idea was proposed for `package.el`, called "package-fastpath", discussed on the mailing list [here](https://lists.gnu.org/archive/html/emacs-devel/2018-02/msg00308.html) and possibly in other places. However, that idea only concatenated all the _autoloads_ into a single file, and not actual package code. Note that `straight.el` implements this concept automatically since over a year ago.

With the filesystem watcher, recipe caching, autoloads caching, and the transaction system, the remaining overhead of `straight.el` is close to zero, and you'd almost certainly be better off looking into other sources of optimization.

**Comment by piotr-yuxuan** [comment]
Wow, thank you very much for that succinct, authoritative reply which kind of exhausts the subject 😂 Also, thank you very much for the added context and the wider vision about such topic.

I shall rephrase this feature request as: could you describe how to achieve faster start-up time with emacs, leveraging modern tooling like `use-package` and `straight.el`? But actually you already outlined that in your last paragraph.

People like you are _very_ enjoyable and impactful for the Emacs community!

**Comment by piotr-yuxuan** [comment]
I doubt I could reach your performance; here is now my init time with 65 packages after I applied the techniques you mentioned:
``` zsh
$ time /Applications/Emacs.app/Contents/MacOS/Emacs --eval '(kill-emacs)'
/Applications/Emacs.app/Contents/MacOS/Emacs --eval '(kill-emacs)'  0.47s user 0.22s system 83% cpu 0.828 total
# (emacs-init-time) => 0.7
```
and here it is with an empty `init.el`:
``` zsh
$ time /Applications/Emacs.app/Contents/MacOS/Emacs --eval '(kill-emacs)'
/Applications/Emacs.app/Contents/MacOS/Emacs --eval '(kill-emacs)'  0.19s user 0.10s system 81% cpu 0.350 total
# (emacs-init-time) => 0.3
```
0.7 isn't that bad, but it's not that good either. What a pity, my current computer is a MacBook Pro (15-inch, 2019) with 32 GB 2400 MHz DDR4 for memory and 2,4 GHz 8-Core Intel Core i9 as processor.

**Comment by raxod502** [comment]
The main thing you want to be sure of is that you're not actually _loading_ any package code during startup. If you `require` something instead of autoloading it, that will be slower. Many packages ask you to load them in order to enable a global minor mode, in which case I use my package [`el-patch`](https://github.com/raxod502/el-patch) to forcibly lazy-load them. Some packages declare too many autoloads (e.g. `gh`), which can be disabled using `:no-autoloads` in the recipe. Putting graphical configuration into the early init-file before the first frame is initialized is a massive startup time boost when you're operating outside of tty mode, although this requires caution as some commands behave contrary to documentation before the first frame is initialized. And of course byte-compilation is the standard thing to do on your init-file, although this requires a great deal of care (I check the mtime on startup and delete stale `.elc` files, then byte-compile asynchronously in the background only after successful startup). You can see what these techniques look like in the source code for [Radian](https://github.com/raxod502/radian).

To be clear, though, the 0.33s is only what `M-x emacs-init-time` reports. The total time to launch and kill is more like 0.55s. Unfortunately, Emacs simply does require a while to start.
