### ISSUE TITLE
Loading "private" packages

### ISSUE THREAD

**Issue by ndw** [raxod502/straight.el#441]
Hello,

The documentation, which is generally excellent, makes it seem like what I'm hoping to do should be possible, but I'm not able to connect the dots.

I'm happy to get most of my packages from github, from melpa, etc. but I have a couple that aren't public. (I suppose, in practice, I could just install them by hand, but I'm trying to simplify my init by doing things in a more regular, less ad hoc fashion).

Can I change the protocol for a single recipe?

What I want to say is "you can get this package by checking out this git repo on that host over ssh".

If that's not possible or is impractical, can I say "you can get this package out of that directory over there?"

**Comment by raxod502** [comment]
Thanks for your question!

Currently, you can't change the protocol for a single recipe (see https://github.com/raxod502/straight.el/issues/92). However, you have two options:

* Just enable SSH globally by setting `straight-vc-git-default-protocol`. All GitHub repositories are accessible via SSH as well as via HTTPS.
* Simply specify the entire URL, i.e. `(:repo "git@github.com:yourname/private.git")` instead of `(:host github :repo "yourname/private")`.

I believe one of these options should solve your problem. However I will also note that you can indeed run a package from a local directory simply using `:local-repo "full-or-relative-path"`. Note that you should put the repository inside `~/.emacs.d/straight/repos` for the automatic modification detection to work the best.

**Comment by ndw** [comment]
Perfect. Thank you. I changed `straight-vc-git-default-protocol` to `ssh` and then this did the trick:

```
(straight-use-package
  '(my-package :repo "ndw@private.example.com:/home/ndw/git/my-package.git"))
```
