### ISSUE TITLE
Failure to detect built-in packages

### ISSUE THREAD

**Issue by svenssonaxel** [raxod502/straight.el#458]
## What's wrong
The code indicates that `straight-use-package` is intended to return successfully after doing nothing, when passed a built-in package. There are some built-in packages where this is not the case.

## Directions to reproduce
```
(straight-use-package 'menu-bar)
(straight-use-package 'tool-bar)
(straight-use-package 'scroll-bar)
(straight-use-package 'uniquify)
```

### Version information

* Emacs version:
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-23, modified by Debian

* Operating system:
Linux d 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Comment by raxod502** [comment]
Well, if you look in `M-x find-library finder-inf`, Emacs seems to say that those features are features but not packages. (Just because you have a feature named `foo` doesn't mean there has to be a package named `foo`; the file `foo.el` is still supposed to have the packaging header either way.) Is there a reason you expect packages by those names to exist, like a `Package-Requires` header that depends on them?

**Comment by svenssonaxel** [comment]
I suppose this was a misunderstanding then, and not a bug.
What about tramp?
It is listed as a built-in package, yet
```
(straight--convert-recipe 'tramp)
->(:type git :host github :repo "emacsmirror/tramp" :package "tramp" :local-repo "tramp")
```

**Comment by raxod502** [comment]
Packages available from recipe repositories always override built-in packages. This is because for example we don't want the Emacs-provided obsolete version of Org to be considered adequate to satisfy a dependency on Org.

**Comment by svenssonaxel** [comment]
Thank you.
