### ISSUE TITLE
Only show packages not installed when using straight-use-package

### ISSUE THREAD

**Issue by rileyrg** [raxod502/straight.el#460]
It would be nice not to see packages already installed when selecting a recipe to install

As an aside, a "remove package" facility would be great... I was battling for hours trying to get org working with straight-use-package only to realise I needed to remove all references to org when starting emacs to stop it being recloned by straight.el.  (I gave up on org from straight.el clone and installed the debian one - way too many undefined this and that when installing from repos).

A wonderful initiative - straight.el flat out rocks.

**Comment by raxod502** [comment]
> It would be nice not to see packages already installed when selecting a recipe to install

That seems reasonable to me.

> As an aside, a "remove package" facility would be great

How would that be implemented? You would need to implement some kind of regex search-and-replace on the user's init-file, and I don't think going down road will end well (see [`package.el`](https://lists.gnu.org/archive/html/emacs-devel/2017-08/msg00154.html)).

> I needed to remove all references to org when starting emacs to stop it being recloned by straight.el

Well, not really. You only need to remove the line that says `(straight-use-package 'org)`, because the explicit purpose of the function `straight-use-package` is to ensure that a package is cloned. Package management state is (mostly) declaratively determined by your init-file, and there isn't (for the most part) any concept of packages being "installed" or not like in `package.el`. So "installing" or "removing" a package just means editing your init-file to include a call to `straight-use-package` or not, and restarting Emacs.

> A wonderful initiative - straight.el flat out rocks.

Thanks!

**Comment by rileyrg** [comment]
Yeah one needs to really understand the bones of what you've created to "get it"... there is a learning curve:)  

But while you're here : frequently there are words to the effect of "temporary installs" - ie using stright-pull-package . Now this clones (I hesiatte to say build or clones at this stage ;)) and one can see it under straight directory. How is this temporary in any way since as far as I see it is never removed by anything even though there is not a "straight-use-package" call for it. They are still picked up from the generated load path are they not so traditional "require" statements can still use them. Undoubtedly I missed something ;) It's a lot to grasp in one go ...

**Comment by raxod502** [comment]
> They are still picked up from the generated load path are they not so traditional "require" statements can still use them.

Actually, that's not true. The package is not deleted from disk, because you might have important changes stored there, but it's no longer part of your configuration. In particular, it is `straight-use-package` that adds a package to `load-path`.

> How is this temporary in any way since as far as I see it is never removed by anything even though there is not a "straight-use-package" call for it.

It's temporary in the sense that the package is no longer accessible from Emacs, unless you invoke `straight-use-package` again in the new session. (See above.)

> frequently there are words to the effect of "temporary installs"

I see now why this is confusing language. With `package.el`, putting a package on disk is the same as adding it to your Emacs configuration, because changes are automatically persisted. That is not the case with `straight.el`.

> ie using stright-pull-package

`M-x straight-pull-package` only offers already-installed packages (where "installed" means "available in the current Emacs session", not "with local repositories present on disk"), and does not interact at all with the clone-and-build system. That is done via `straight-use-package`.

> It's a lot to grasp in one go ...

Understandable. I do know it is a lot. Hopefully this helps.

**Comment by rileyrg** [comment]
Helps very much. I'm glad I made the transition. Excellent stuff.

**Comment by progfolio** [comment]
We now have both features requested.
