### ISSUE TITLE
Expected development workflow?

### ISSUE THREAD

**Issue by progfolio** [raxod502/straight.el#463]
Not sure if I've encountered a bug or just have a misunderstanding of the expected workflow when developing a package while using straight. I currently have straight configured to check for file modifications using watchexec. My use case:

I'm developing an Emac's package. I edit the source file for the package in the straight/repos/my-package/ directory. Is straight supposed to reload that package in the current Emacs instance, or am I supposed to start a fresh instance to test the rebuilt package? In my case, it is only rebuilt when Emacs is restarted or a fresh instance is started. I expected straight to reload the package after rebuilding in the current Emacs instance. Possibly related to #432, but I wanted to make sure my expectations are correct before adding to that bug report.

**Comment by raxod502** [comment]
No, there is no support provided for "reloading" a package, because it's generally expected that you will do this yourself by evaluating the functions that you changed. In general, Emacs doesn't provide a facility for reloading a package -- that's not an abstraction that it's really set up to deal with. Even if I were to add a facility whereby `straight.el` could forcibly reload a certain subset of Elisp files from the package, it wouldn't be robust: some changes to the package won't take effect, like for example changes to the default values of variables. It's possible to cause those changes to take effect, but you have to know what has changed and act accordingly. For that reason, I think it's best to leave this part to the user, like all other existing Emacs package managers do.

My development workflow is to write some code, then use commands such as `eval-defun` and `eval-buffer` to evaluate the updated code. I may follow some extra steps if I'm working with a package that has persistent state that needs to be updated. But after I manually evaluate the new code, I can test it out immediately, without needing to restart.

Does that answer your question? If so, perhaps that information could be added to the documentation.

**Comment by progfolio** [comment]
It does. In my particular case the compiled version of the package was shadowing what I thought I was calling. I was able to unload the library and get back to the eval workflow you've described. Thank you for the explanation, and thank you for the awesome package manger.

**Comment by raxod502** [comment]
I added a section to the README to include this important information.
