### ISSUE TITLE
(straight-use-package 'f) still requires me to do (require 'f) in order to use the `f' library

### ISSUE THREAD

**Issue by a-schaefers** [raxod502/straight.el#466]
## What's wrong
I might be barking up the wrong tree here, is this actually a problem with `f'?

Currently my config looks like this:
(straight-use-package 'f)
(require 'f)

It's weird to me because this is the only package I have had to to do this with.

Thanks for making straight by the way. I've had the weirdest melpa issues in the past, where  package update breaks my entire setup, with unclear messages regarding which package was at fault, and no clear way to to revert. It was the wild west!

### Version information

* Emacs version:
* Operating system:

**Comment by a-schaefers** [comment]
I just read on the README

> Note that installing a package will activate all of its autoloads, but it will not actually require the features provided by the package. This means that you might need to use require or autoload for some antiquated packages that do not properly declare their autoloads.

I guess I am barking up the wrong tree, then. Sorry

**Comment by raxod502** [comment]
It is worth noting that `f` is not an antiquated package. It is standard for utility libraries to not declare autoloads, because only interactive commands or functions that are directly run as a consequence of interactive commands should be autoloaded. It is expected that if your package provides an interactive command and it needs `f`, it should autoload its own command and then `(require 'f)` before defining the command.
