### ISSUE TITLE
Remove or uninstall package

### ISSUE THREAD

**Issue by billop** [raxod502/straight.el#517]
Is this already possible? Can't find anything on it.

**Comment by herrsimon** [comment]
I was searching for the same thing. Apparently this feature is still missing. If I understand correctly, you can do it manually by deleting the respective package directories from `build`, `repos`, `modified` (if present) and then delete the entries in `build-cache.el`. Doing this manually is of course very inconvenient, also because you have to follow the same procedure for all dependencies which might have been installed (which typically should be removed as well).

I think the best solution is to write a 'straight-remove-package' function which does all of this automatically. The only slightly involved thing would be to implement proper dependency tracking, but as a quick interim solution one could simply find those which are not used by any other installed package and then query the user whether they should be removed.

**Comment by raxod502** [comment]
Does the new FAQ entry answer your question?

**Comment by herrsimon** [comment]
It does, thanks a lot!

**Comment by zoechi** [comment]
The referenced FAQ entry is https://github.com/raxod502/straight.el#how-do-i-uninstall-a-package

It seems I was just running in an issue like #2377 and was looking for how to uninstall.

**Comment by memeplex** [comment]
Hi, just a heads-up, the FAQ is outdated, it's referencing a function that was recently obsoleted.

**Comment by progfolio** [comment]
Noted in #671
