### ISSUE TITLE
org-roam package

### ISSUE THREAD

**Issue by OrionRandD** [raxod502/straight.el#522]
I am also have issues to install org-roam with straight 
use-package also does not work. 
Tried to follow these steps:

https://org-roam.readthedocs.io/en/master/installation/

**Comment by OrionRandD** [comment]
straight-get-recipe for org-roam does not work also :(

**Comment by raxod502** [comment]
Please refer to the new FAQ entry: https://github.com/raxod502/straight.el/tree/a7f94876b2bf96d2595706270be6630ecc94f0d3#could-not-find-package-in-recipe-repositories

**Comment by OrionRandD** [comment]
Now my issue is with https://github.com/org-roam/org-roam-server
org-roam-server
Cannot find it on straight  :( 
Could you add the recipe?
Thx a lot

**Comment by raxod502** [comment]
It's on MELPA. Please follow the directions in the FAQ entry.

**Comment by OrionRandD** [comment]
Ok. Thx

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
