### ISSUE TITLE
Renaming master branches

### ISSUE THREAD

**Issue by jcf** [raxod502/straight.el#540]
Hi there,

There's some discussion over in the Doom repo because an Emacs package that we clone from GitHub has renamed its master branch to main, and this has broken the installation/update process in Doom.

https://github.com/hlissner/doom-emacs/issues/3435
https://github.com/ahyatt/emacs-websocket/issues/69

I expect we might see the `master` branch convention diminish over the coming months, and wonder if adding support for explicitly naming branches might be a necessary fix…

**Comment by raxod502** [comment]
There _is_ already support for explicitly naming branches. Just put `:branch <whatever>`. The problem is that `straight.el` lacks support for correctly determining what the _default_ branch name is if it's _not_ specified. The reason this is nontrivial is because now determining the default branch name requires network IO instead of being a thing we know instantly.

This is discussed at #279.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
