### ISSUE TITLE
Symbols not defined in boostrap/install

### ISSUE THREAD

**Issue by katandtonic** [raxod502/straight.el#542]
## What's wrong

Bootstrap script yields:

```
error: straight.el bootstrap failed: Symbol’s function definition is void: straight--windows-os-p
```

If the only invocation of this function is removed from the bootstrap file is removed, then other variables/functions appear to be undefined.

## Directions to reproduce
init.el
```
(let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el"))
      (bootstrap-version 2))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
       "https://raw.githubusercontent.com/raxod502/straight.el/master/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq package-enable-at-startup nil
      straight-use-package-by-default t
      straight-vc-git-default-protocol 'ssh)
(straight-use-package 'use-package)
(require 'use-package)
(setq use-package-enable-imenu-support t)
(setq use-package-ensure-function 'straight-use-package-ensure-function)
```

### Version information

* Emacs version: Emacs 26.3
* Operating system: NixOS

**Comment by raxod502** [comment]
Thank you for the report. It should be fixed now.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)

**Comment by NicoloZorzetto** [comment]
> This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)

Hello, it has been more than 3 years but I am finding the same problem.
I am using emacs29.1 and emacs28.1 (different machines). In my init I have:

```
  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	(bootstrap-version 6))
	 (expand-file-name
	  "straight/repos/straight.el/bootstrap.el"
	  (or (bound-and-true-p straight-base-dir)
	      user-emacs-directory)))
	(bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
```

At first run (empty .emacs.d directory except from init) everything works fine, but if i try to evaluate this snippet after it gives:

`progn: Symbol’s function definition is void: bootstrap-version`

Moreover, i backup my entire .emacs.d thru git. When doing so .emacs.d/straight/repos/straight.el gets committed as an empty directory and thus the other devices give 'No such file or directory: .../bootstrap.el'.
This is not fixed by the `(unless (file-exists-p bootstrap-file) [...]`, not sure why.
Adding straight.el as a git submodule also doesn't fix the backup-problem.
