### ISSUE TITLE
Do I have to declare all `straight-use-package` as early as possible?

### ISSUE THREAD

**Issue by adrianparvino** [raxod502/straight.el#560]
I'm in the process of cleaning up my `.emacs`, and would like to separate it into sections, maybe convert it to a literate config. Are there any caveats regarding running additional code in between `straight-use-package`s?

**Comment by raxod502** [comment]
No, although obviously you won't be able to load a package until after it's been pulled in with `straight-use-package`. See [my configuration](https://github.com/raxod502/radian/blob/develop/emacs/radian.el) for an example.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
