### ISSUE TITLE
Now incorrect statement about package.el in README

### ISSUE THREAD

**Issue by skangas** [raxod502/straight.el#579]
This statement in README is no longer true in Emacs 27.1:

> straight.el considers modifying the user's init-file extremely uncouth. package.el aggressively inserts a call to package-initialize into the init-file if it is not already present, whenever any package management operation is performed.

**Comment by raxod502** [comment]
Thank you for pointing out the problem. Luckily, I can still nail it on `package-selected-packages` :sparkles: (unless somebody fixed that too without my noticing :)

**Comment by skangas** [comment]
> Luckily, I can still nail it on `package-selected-packages` sparkles (unless somebody fixed that too without my noticing :)

That's true for any package that uses custom, including straight.el, right?

Feel free to close this if you disagree. Thanks for your time!

**Comment by raxod502** [comment]
> That's true for any package that uses custom, including straight.el, right?

No quite. While `straight.el` does use `defcustom`, there is no requirement for those variables to be set using Custom. In fact, I would actively recommend against it. The problem with `package.el` is that it automatically sets the variable using Custom when you install a package, which forces the init-file to be modified even if you otherwise did not use Custom at all.
