### ISSUE TITLE
Drop support for 24.5?

### ISSUE THREAD

**Issue by progfolio** [raxod502/straight.el#635]
According to https://www.gnu.org/software/emacs/history.html

> 2015-04-10 - Emacs 24.5 released

Coming up on six years for that release and most of our compatibility code (shims for if-let, when-let, backquote requirements in pcase statements) could be phased out if we bump our minimum version to 25.1 (released 2016-09-17).

Not scientific by any means, but a recent poll shows a majority of users well beyond that version:

https://www.reddit.com/poll/imwewj?utm_source=reddit&utm_medium=usertext&utm_name=emacs&utm_content=t3_imwewj

Another survey is open until 2020-11-30:

https://emacssurvey.org/

I think it'd be useful to see the results of this survey, as I suspect it was more widely promoted and will have more participants.

I also realized that 24.5 does not have support for `make-process`, so unfortunately we lose `straight-bug-report` on that version and it may complicate the implementation of #76 (depending on our approach).

Thoughts?

**Comment by raxod502** [comment]
Yep, I'd say it's totally safe to drop 24.5. It is, indeed, quite ancient :D 
It is actually pretty rare to find _any_ package that supports 24.5 these days, and I think more than once the smoke test in CI for `straight.el` broke because the package being installed as a test stopped supported that version.

**Comment by progfolio** [comment]
Taken care of w #636
