### ISSUE TITLE
Modifying straight repos

### ISSUE THREAD

**Issue by haji-ali** [raxod502/straight.el#698]
I am using straight to download and use my forks of emacs packages. 
Instead of having several copies of my repository (one managed by me where I make my changes and one managed by straight), I thought I can configure straight to download the repo (into the `repos` directory) and then navigate to it when I want to modify my code. However, I am unsure about this workflow for the following reasons:
- When navigating to my repository under the `repos` folder, the git clone seems incomplete (?). For one thing if I check the git history only the last commit is there.
- After modifying the code, committing and pushing the changes, I don't know how to initiate the `pre-build` actions of that I configured in `straight` so that the package is updated and re-built.

Is this an acceptable use-case of straight? How do I correctly setup such a workflow?

**Comment by progfolio** [comment]
> When navigating to my repository under the repos folder, the git clone seems incomplete (?). For one thing if I check the git history only the last commit is there.

In this case, I would check the value of `straight-vc-git-default-clone-depth`. Perhaps it is set to `1` instead of `full`? Keep in mind this may be set on a per-recipe basis via the `:depth` keyword as well.

> After modifying the code, committing and pushing the changes, I don't know how to initiate the pre-build actions of that I configured in straight so that the package is updated and re-built.

After modifying the files and saving, you can run `M-x straight-rebuild-package`. The `:pre-build` commands should be run in this case (please let me know if they do not). If you have the filesystem watcher enabled, you can also restart Emacs, or start a new instance of Emacs and straight should rebuild the modified packages during init.

Hope this helps. Let me know if you have any other questions.

**Comment by progfolio** [comment]
The information in this thread may be useful to you as well:
https://github.com/raxod502/straight.el/issues/679
