### ISSUE TITLE
Support texinfo

### ISSUE THREAD

**Issue by raxod502** [raxod502/straight.el#71]
`straight.el` should build texinfo manuals during the build step. This should be doable as a constant step after building.

**Comment by LdBeth** [comment]
OR enable custom building commands at per-package base to support noun standard packages?

**Comment by raxod502** [comment]
That is also planned, see #72. But for compatibility with MELPA, we need to build texinfo at the top level automatically.

**Comment by mnewt** [comment]
I'm trying to get a handle on the mechanics of this:
- [ ] Would we run makeinfo from the command line? GNU seems to recommend that, but perhaps we should fall back to emacs builtin functions.
- [ ] Where would the Info files go once they are built? I think it should be somewhere in $HOME, since it seems like a bad idea for packages to modify system-wide places like `/usr/local/share/info`. Maybe create an `~/.emacs.d/straight/info` directory?
- [ ] How do we make emacs aware of the info files? I'm having trouble understanding the best way. There are at least three ways: `INFOPATH` environment variable, `info-default-directory-list`, and `info-directory-list`.

**Comment by raxod502** [comment]
> Would we run makeinfo from the command line?

Not sure. I would defer to whatever el-get, Borg, and package.el do.

> perhaps we should fall back to emacs builtin functions.

Are there such functions? If so, it sounds like a good idea to use them. This is something I haven't researched yet.

> Where would the Info files go once they are built?

I would have assumed that they would go into the same directory as the built package, which is then added to `Info-directory-list`, just like it's already added to `load-path`.

> Maybe create an ~/.emacs.d/straight/info directory?

Putting it in the per-package build directories means we bypass questions of how to identify and remove info files for packages which are no longer in use.

> How do we make emacs aware of the info files?

The `INFOPATH` environment variable is for use by the end user externally to Emacs, and not for Emacs packages. `Info-default-directory-list` is for system use, i.e. by the system package manager. It's `Info-directory-list` that we want.

**Comment by raxod502** [comment]
Ah, I see that you probably meant we would have a `~/.emacs.d/straight/info/<package>` directory for each package. That would make sense, but it would probably accomplish the same to just put them in the existing `~/.emacs.d/straight/build/<package>` directories.

**Comment by raxod502** [comment]
Please open a new issue if you find that your favorite package's texinfo manuals are not available. (Except for ESS and Org, which just _have_ to be special, and will need both #72 and #115 to be solved in order to work.)
