### ISSUE TITLE
Is there any way to excecute :post-build with `sudo`?

### ISSUE THREAD

**Issue by Lodger** [raxod502/straight.el#725]
Hello, I have this recipe for EMMS:

``` elisp
'(emms
   :type git
   :flavor melpa
   :files ("*.el" "lisp/*.el" "doc/emms.texinfo" "emms-pkg.el" "src/*")
   :repo "https://git.savannah.gnu.org/git/emms.git"
   :post-build (("make" "emms-print-metadata") ("mv" "src/emms-print-metadata" "/usr/local"))))
```
However, to run `mv src/emms-print-metadata /usr/local`, I need root permission via `sudo`. Is there anyway to do this?

**Comment by progfolio** [comment]
Is the goal to run the command as root without any prompt for your password, or do you want to be prompted for  your password?

**Comment by Lodger** [comment]
ideally I would like to be prompted, but either way would be acceptable

**Comment by progfolio** [comment]
`:post-build` commands can be arbitrary elisp or system processes. I haven't tried it, but you may be able to set up an askpass program and write a script which prompts for a password when you need it.

**Comment by raxod502** [comment]
Yep, that would be the way to do it. `straight.el` won't be able to do a tty prompt (due to complications with how async processes work), so you'll need some additional configuration.

That said, might it be a better idea to reconfigure whatever dependency wants the EMMS stuff installed in `/usr/local` so that it can read the configuration out of your home directory instead? That seems like it could potentially be cleaner.

**Comment by Lodger** [comment]
This was the perfect solution, didn't realize i could customize `emms-info-libtag-program-name` :p, thanks!
