### ISSUE TITLE
Straight rebuilding critera : emacs version/host and native compile

### ISSUE THREAD

**Issue by rileyrg** [raxod502/straight.el#749]
I have my emacs set up in dropbox shared across various machines - including repo and build. 

I've noticed that sometimes straight determines a full rebuild is necessary at startup when I startup emacs on another synced machine. Why would that be? Does it force a rebuild if it determines (possibly) a different emacs version?

Also, I'd like to debug a native compile emacs - but of course this triggers a full rebuild too - would it be sufficient for me to modify my straight-build-dir to be host and emacs version unique to stop this? If so it strikes me this might be a good "base product" enhancement via optional setting,  I see that straight already handles native compilation and that the binaries are cached in emacs directory/.eln-cache/$VERSION/* which is good - so we don't need to re native compile for each version.

**Comment by rileyrg** [comment]
closing this as the rebuild issue has magically vanished. ;)

**Comment by raxod502** [comment]
Yes, changing Emacs version forces a full recompilation of all packages. This is because files that are byte-compiled on one version of Emacs don't always work on other versions of Emacs, even if the underlying code is compatible with both versions.

> would it be sufficient for me to modify my straight-build-dir to be host and emacs version unique to stop this?

Yes, that's exactly the solution if you want to use the same `~/.emacs.d` with multiple versions of Emacs concurrently. It would be great to set up the paths so that this is taken care of by default, or at least so there is a user option one can set to enable that behavior.

> the binaries are cached in emacs directory/.eln-cache/$VERSION/*

That's actually a feature of native-compilation itself, not something added by `straight.el`.

**Comment by raxod502** [comment]
https://github.com/raxod502/straight.el/blob/253d7db6c1165741208219e7b3a29beb12dcd731/straight.el#L3957-L3965

**Comment by rileyrg** [comment]
Informative, thank you.
