### ISSUE TITLE
Pass the relevant valules obtained by straight's variable/function to the shell commands used in pre-build section.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#800]
According to the instruction given in auctex's INSTALL file, I compose the following lisp snippet for using it from local Git repo:

```emacs-lisp
(straight-use-package
 `( auctex :type git :host nil :repo "https://git.savannah.gnu.org/git/auctex.git"
    :pre-build ,(pcase system-type
                (`berkeley-unix '("gmake"))
                (_ '(
                    ("bash" "-c" "cd ~/.emacs.d/straight/repos/auctex")
                    ("./autogen.sh")
                    ("./configure" "--without-texmf-dir" "--with-lispdir=.") 
                    ("make")
                    )))))

     (setq TeX-data-directory (straight--repos-dir "auctex")
           TeX-lisp-directory TeX-data-directory)

     (eval-after-load 'info
        '(add-to-list 'Info-additional-directory-list
                      (concat (straight--repos-dir "auctex") "doc")))

(load "auctex.el" nil t t) 
(load "preview-latex.el" nil t t)
(setq TeX-auto-save t)
(setq TeX-parse-self t)
(setq-default TeX-master nil)
```
As we [have discussed before](https://github.com/raxod502/straight.el/issues/793#issuecomment-860304893), the lisp code line below is needless due to `straight.el`'s inner operation mechanism:

`("bash" "-c" "cd ~/.emacs.d/straight/repos/auctex")`

But from a technical point, I want to know if I can pass straight's function result, i.e., `(straight--repos-dir "auctex")` to the above shell command for convenient variable substitute.

Regards,
HY

**Comment by progfolio** [comment]
```emacs-lisp
 (eval-after-load 'info
        '(add-to-list 'Info-additional-directory-list
                      (concat (straight--repos-dir "auctex") "doc")))
```

Should be unnecessary. Straight has it's own mechanism to build and install info for packages.
If you inspect the value of the variable `Info-directory-list` you should see directories under `.../straight/build/` added to it.

> But from a technical point, I want to know if I can pass straight's function result, i.e., (straight--repos-dir "auctex") to the above shell command for convenient variable substitute.

This is a general elisp question. Since the entire recipe is in a backquoted list, I would read up on the following:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html

**Comment by hongyi-zhao** [comment]
> Should be unnecessary. 

Thank you for letting me know this.

> Since the entire recipe is in a backquoted list,

Based on your hints, I tried out the following expression in the `*scratch*` buffer:

`(shell-command "bash" "-c" `("cd" (straight--repos-dir "auctex")))`

So the corresponding code line used in `~/.emacs.d/init.el` should look as below:

`("bash" "-c" `("cd" (straight--repos-dir "auctex")))`

**Comment by raxod502** [comment]
As a side note,

```
`("bash" "-c" "cd" ,(straight--repos-dir "auctex"))
```

is not doing anything. The `cd` directive modifies the local environment of a shell session, and its effects expire as soon as Bash exits, so it doesn't affect any of the subsequent commands you run. Luckily, the working directory is already set correctly by `straight.el`, which is how your current code is working, so you can just remove that list element.

**Comment by hongyi-zhao** [comment]
> Luckily, the working directory is already set correctly by `straight.el`, which is how your current code is working, so you can just remove that list element.

But what should I do if I want to work on a different directory to the one set by `straight.el`?

**Comment by raxod502** [comment]
I'd recommend (untested):

```
`("bash" "-c" "cd \"$1\" && whatever-command" "--" ,some-other-directory)
```

**Comment by progfolio** [comment]
`:pre-build` steps can also use elisp, so it's possible to bind `default-directory` and then call a shell command from that context.e.g.

* Yodel Report [2021-10-03 15:24:46]

#+begin_src emacs-lisp :lexical t :results silent
(yodel
  :packages*
  (doct
   :pre-build
   ((let
        ((default-directory
           (expand-file-name "../" default-directory)))
      (print
       (shell-command-to-string "pwd"))))))
#+end_src

** STDOUT:

#+begin_src emacs-lisp :lexical t :results silent
Loading /tmp/yodel-YlIyqo/straight-bootstrap-snippet.el (source)...
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done
Cloning doct...
Cloning doct...done
Building doct...

"/tmp/yodel-YlIyqo/straight/repos
"
Building doct...done
#+end_src

** Environment

- =emacs version=: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-09-29
- =system type=: gnu/linux

*** Packages

| Name | Branch | Commit     |       Date | Source |
|------+--------+------------+------------+--------|
| [[https://github.com/progfolio/doct][doct]] | master | [[https://github.com/progfolio/doct/commit/fe7ec7cf99608412073d2d68885577b9135a94ac][fe7ec7cf99]] | 2021-09-25 | melpa  |

**Comment by hongyi-zhao** [comment]
See my currently used auctex installation and configuration code given [here](https://github.com/raxod502/straight.el/issues/836#issuecomment-927098560).

**Comment by hongyi-zhao** [comment]
> I'd recommend (untested):
> 
> ```emacs-lisp
> `("bash" "-c" "cd \"$1\" && whatever-command" "--" ,some-other-directory)
> ```

Based on your suggestion above, I tried to use the following code snippet for vterm module compilation:

```emacs-lisp
(use-package vterm
  :straight (
	     :pre-build (
			 ("rm" "-fr" "build")
			 ("mkdir" "build")
			 `("bash" "-c" "cd \"$1\" && cmake .. && make" "--"  ,(concat (straight--repos-dir "emacs-libvterm") "build"))
			 )))
```

But what surprised me was that the above method doesn't work, while the evaluated result works when I run `M-x straingt-rebuild-package RET vterm RET`:

```emacs-lisp
(use-package vterm
  :straight (
	     :pre-build (
			 ("rm" "-fr" "build")
			 ("mkdir" "build")
			 ("bash" "-c" "cd \"$1\" && cmake .. && make" "--"  "/home/werner/.emacs.d/straight/repos/emacs-libvterm/build")
			 )))
```

See [here](https://github.com/raxod502/straight.el/issues/891#issuecomment-984438357) for the related comment.

**Comment by hongyi-zhao** [comment]
> Should be unnecessary. Straight has its own mechanism to build and install info for packages.
> If you inspect the value of the variable `Info-directory-list` you should see directories under `.../straight/build/` added to it.

Today, I rechecked the above variable and find the following entry in it:

`"/home/werner/.emacs.d/straight/build/auctex/"`

But I still can't find the auctex entry in the INFO tree.
