### ISSUE TITLE
SSH clone and/or HTTPS clone

### ISSUE THREAD

**Issue by agsdot** [raxod502/straight.el#81]
Hi @raxod502 ,

When setting up a new computer, I like to clone my emacs dotfiles. However, if I don't have my .ssh keys setup with github, I'm unable to do a straight.el .emacs.d setup as it requires the ssh git for cloning git@github.com:username/project.git (other projects other than straight.el, e.g. projectile, magit, etc) . Naturally I should just setup ssh keys, but what if it's the scenario of you're spinning up a bunch of aws servers, and setting up ssh keys on the remote host is just a bother.

If I do an el-get .emacs.d setup it is able to proceed because it allows using an https git clone.  What do you think about putting a setting/parameter to allow https on initial git clone.

P.s. Here's also another thought, and I'm not sure how this would be done. Never really done this with git except manually. Can it be automated so that the git remote changes from using https to ssh. Manually I normally just do "git remote rm origin (some https remote)" and then "git remote add origin git@github.com:username/project.git" .

**Comment by raxod502** [comment]
The relevant logic is in [`straight--vc-git-encode-url`](https://github.com/raxod502/straight.el/blob/9551e21e9459639e0a37b1552d0d201924eaa198/straight.el#L665-L681), which is what handles constructing a URL from `:host` and `:repo` for the `git` backend. As you can, it's hardcoded to generate SSH URLs at the moment. That can and should be changed to allow for generating HTTPS URLs by default, by the introduction of a `straight-vc-git-default-protocol` user option.

By default, whatever URL the repository is cloned from becomes the URL of the remote. When you use `straight.el` to perform bulk management of your repositories, it will interactively make sure that your remote URLs are set correctly, but by default it treats HTTPS and SSH URLs equivalently, using [`straight--vc-git-urls-compatible-p`](https://github.com/raxod502/straight.el/blob/9551e21e9459639e0a37b1552d0d201924eaa198/straight.el#L705-L712). People with strong opinions about HTTPS vs. SSH can be accommodated by the addition of a `straight-vc-git-force-protocol` user option, which would cause HTTPS and SSH URLs to be treated as non-equivalent, so they would be reset to the protocol that you specified.

**Comment by agsdot** [comment]
Thanks @raxod502, I appreciate it.

Having it so that it so that one can bootstrap and clone one's emacs.d files and use purely https will be convenient (for the unprovisioned computer).

With regards to package development, I totally understand the ssh git@github.com:username/projectname.git default format -- I much prefer it vs https normally. Less bothersome logins to github/bitbucket, etc that the https remote occasionally prompt one for.

**Comment by agsdot** [comment]
P.s. Out of curiosity, how would one automate changing remotes from using ssh remote to https? Both in the shell / bash and in elisp? Or https to git? If you've got the bash tool for this it would be perfect for [git-extras](https://github.com/tj/git-extras).

**Comment by raxod502** [comment]
Hmm… it shouldn't be terribly difficult. Firstly you can use `git remote set-url` instead of deleting and re-creating the remote, although it might be preferable to delete and then recreate since then you don't have to worry about out-of-date branch pointers. See [`straight--vc-git-validate-remote`](https://github.com/raxod502/straight.el/blob/9551e21e9459639e0a37b1552d0d201924eaa198/straight.el#L722-L806) for how this is handled interactively in `straight.el`.

Obviously doing it for GitHub, GitLab, and Bitbucket repositories is not hard, but I do not know of a general way to translate from HTTPS to SSH. If you figured out a good heuristic, though, it's just a matter of using `git remote get-url` and `git remote set-url`.

**Comment by agsdot** [comment]
P.s. Out of curiosity, how would one automate changing remotes from using ssh remote to https? Both in the shell / bash and in elisp? Or https to git? If you've got the bash tool for this it would be perfect for [git-extras](https://github.com/tj/git-extras).

**Comment by raxod502** [comment]
@agsdot Please let me know what you think of the latest version (https://github.com/raxod502/straight.el/commit/361eed5f439fcd6974f71aed66f4f6482f7cc798).

**Comment by agsdot** [comment]
:+1: @raxod502, commit 361eed5 provides for what I asked for in the original issue, now I can clone my .emacs.d on a server without the public/private key files setup, and all the packages are cloned using https rather than ssh.

I tested setting the parameter 
(setq straight-vc-git-default-protocol 'https)
and 
(setq straight-vc-git-default-protocol 'ssh)
and they worked fine from a fresh install of straight.el (i.e. I blew out the straight/ directory and went for the fresh install).

How do you force for an already initialized .emacs.d with the repos already downloaded for the packages to switch remotes from the ssh to https format? Changing setq straight-vc-git-default from 'ssh to 'https back and forth on an already initialized repo didn't change/update the remotes.  

Note, this is an entirely non-necessary request now, just asked out of curiosity and for convenience (I can just rm -rf the straight/ directory and let it download and build again), it would be convenient though if just for the sake of not having to clone all the repos again.

Thanks!

**Comment by raxod502** [comment]
You can use `M-x straight-normalize-all`, which is provided for the express purpose of performing these kinds of normalization tasks. Note that if you want HTTPS and SSH URLs to be considered as incompatible (so that `straight.el` will prompt you to re-set remote URLs that are using the "wrong" protocol), you must `(setq straight-vc-git-force-protocol t)`.

By design, you should never ever have to delete the entire `straight` directory: it contains all of your repositories and your version lockfiles!

**Comment by agsdot** [comment]
It works! Thanks @raxod502 .
