### ISSUE TITLE
Support :type nil?

### ISSUE THREAD

**Issue by progfolio** [raxod502/straight.el#844]
Confirmed with the following:

[YODEL](https://github.com/progfolio/yodel) REPORT (2021-09-18 17:59:12):

<details> <summary>Test Case:</summary>

```emacs-lisp
(yodel
  :save t
  :user-dir "local-repo-test.straight"
  :formatter yodel-format-as-github-markdown
  :post*
  (yodel-file "./local-repo/local-repo.el"
    :save t
    :overwrite t
    :with*
    ";;;###autoload"
    (defun local-repo-test nil
      (message "PASS"))
    (provide "local-repo"))
  "Straight bootstrap code"
  (defvar bootstrap-version)
  (let
      ((bootstrap-file
        (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
       (bootstrap-version 5))
    (unless
        (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           (concat "https://raw.githubusercontent.com/" "raxod502/straight.el/develop/install.el")
           'silent 'inhibit-cookies)
        (goto-char
         (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
  (condition-case nil
      (message "Test run with version: %s"
               (straight-version))
    (error nil))
  "End bootstrap"
  (straight-use-package
   '(local-repo-test
     :local-repo "./local-repo"
     :type nil))
  (local-repo-test))
```

</details>
<details>
  <summary>STDOUT:</summary>

```emacs-lisp
Test run with version: prerelease (HEAD -> master, origin/master, origin/HEAD) 1e27b05 2021-06-13
Cloning ./local-repo (for local-repo-test)...
```

</details>

<details>
  <summary>STDERR:</summary>

```emacs-lisp
(error "No such VC backend ‘nil’")
```

</details>

<details>
  <summary>Environment</summary>

- **emacs version**: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-09-16
- **system type**: gnu/linux

</details>

I've never used a recipe in this way. Indeed it does look like specifying `:type nil` will fail during `straight-vc`.
It looks like this behavior would require implementing a VC backend called "nil" according to:
19c34fc96b3668d2b1266cf18fb8008903c5c98b

@raxod502: Is this a use case we want to support?

_Originally posted by @progfolio in https://github.com/raxod502/straight.el/issues/671#issuecomment-922380449_

**Comment by raxod502** [comment]
Looking at that commit which I authored in 2019, it seems a little silly to me now. It seems like `:type nil` should disable all version control operations for the package, similarly to `:type 'built-in`, since anything else feels surprising. However, I would expect that `:type nil`, unlike `:type 'built-in`, would still load the package from its default directory, it would just disable version control operations. So you'd basically be saying, please load this package per normal, but don't assume it's managed by Git or any other version control system.

I'm not sure if this fully works, but I submitted https://github.com/raxod502/straight.el/pull/885 which I think makes the behavior at least more reasonable, and makes it clear how things are supposed to work.
