### ISSUE TITLE
The `:includes` keyword used in the recipe doesn't generate the corresponding sub-package.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#919]
On Ubuntu 20.04.3 LTS, I'm using the self compiled git master Emacs, and try to install [emacs-native-shell-complete](https://github.com/CeleritasCelery/emacs-native-shell-complete) with the following configuration following the guides [here](https://github.com/CeleritasCelery/emacs-native-shell-complete#1-emacs-setup) and [here](https://github.com/CeleritasCelery/emacs-native-shell-complete#2-shell-setup):

```emacs-lisp
;; https://melpa.org/#/native-complete
;; https://melpa.org/#/company-native-complete
;; https://github.com/CeleritasCelery/emacs-native-shell-complete#1-emacs-setup
(use-package native-complete
  :straight (:host github :repo "CeleritasCelery/emacs-native-shell-complete"
		   ;; https://github.com/raxod502/straight.el#the-recipe-format
		   ;; :includes indicates a package is a superset of another package.
		   :includes company-native-complete
		   )
  ;; https://github.com/CeleritasCelery/emacs-native-shell-complete#2-shell-setup
  :config
  (with-eval-after-load 'shell
    (native-complete-setup-bash))
  )
```
But I only find the `native-complete.el` is created under the built package directory, as shown below:
```
$ ls /home/werner/.emacs.d/straight/build/native-complete/
native-complete-autoloads.el  native-complete.el  native-complete.elc
```
Any hints for this problem?

Regards,
HZ

**Comment by progfolio** [comment]
Since you haven't specified any `:files`, it's probably picking them up from MELPA. You should set the `:files` directive to include the files you want. e.g. `:files (:defaults)`. Tested with the following:

[Yodel](https://github.com/progfolio/yodel) Report (2022-01-15 11:07:23):

```emacs-lisp
(yodel
  :packages*
  (native-complete
   :host github
   :repo "CeleritasCelery/emacs-native-shell-complete"
   :files (:defaults)
   :includes company-native-compile)
  :post*
  (let ((default-directory (straight--build-dir "native-complete")))
    (message "%S" (shell-command-to-string "ls"))))
```

<details><summary>STDOUT:</summary>

```emacs-lisp
Loading /tmp/yodel-tWqqwT/straight-bootstrap-snippet.el (source)...
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe -> Cloning melpa...
Looking for gnu-elpa-mirror recipe -> Cloning melpa...done
Looking for emacsmirror-mirror recipe -> Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe -> Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe -> Cloning el-get...
Looking for emacsmirror-mirror recipe -> Cloning el-get...done
Looking for straight recipe -> Cloning emacsmirror-mirror...
Looking for straight recipe -> Cloning emacsmirror-mirror...done
Building straight...
Building straight...done
Cloning emacs-native-shell-complete (for native-complete)...
Cloning emacs-native-shell-complete (for native-complete)...done
Building native-complete...
Building native-complete...done

"company-native-complete.el
native-complete-autoloads.el
native-complete.el
native-complete.elc
"
```

</details>
<details><summary>Environment</summary>

- **emacs version**: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4)
 of 2022-01-13
- **system type**: gnu/linux

<details open><summary>Packages</summary>

| Name                                                                              | Branch | Commit                                                                                                         | Date       | Source |
|-----------------------------------------------------------------------------------|--------|----------------------------------------------------------------------------------------------------------------|------------|--------|
| [native-complete](https://github.com/CeleritasCelery/emacs-native-shell-complete) | master | https://github.com/CeleritasCelery/emacs-native-shell-complete/commit/20e1dceb459856c8c4f903e6d8562991069bb8c1 | 2022-01-03 | melpa  |

</details>

</details>

**Comment by hongyi-zhao** [comment]
> It looks like in this case, they are provided.

It seems that you are right, based on further checking with your suggested configuration:
```
werner@X10DAi-00:~/.emacs.d/straight/build/native-complete$ grep '^(autoload' native-complete-autoloads.el 
(autoload 'company-native-complete "company-native-complete" "\
(autoload 'native-complete-setup-bash "native-complete" "\
(autoload 'native-complete-at-point "native-complete" "\
```
