### ISSUE TITLE
Straight seems to fill /tmp with empty straight-stderr-* files

### ISSUE THREAD

**Issue by ajakk** [raxod502/straight.el#939]
## What's wrong

Every time I open emacs, a new empty file is created in tmp of the format `straight-stderr-${EMACSPID`

## Directions to reproduce

Make a fresh `~/.emacs.d`, then add the README's [elisp snippet](https://github.com/raxod502/straight.el#getting-started) to `~/.emacs.d/init.el`, then launch emacs. A file in /tmp will appear with a filename of the format `straight-stderr-${EMACSPID}`. After opening a few Emacs instances, I can see:

```
~ $ ls /tmp/straight-stderr*
/tmp/straight-stderr-2428693  /tmp/straight-stderr-2430175  /tmp/straight-stderr-2504443  /tmp/straight-stderr-2507556  /tmp/straight-stderr-2510705  /tmp/straight-stderr-2515796  /tmp/straight-stderr-2516565  /tmp/straight-stderr-2516884  /tmp/straight-stderr-2577560
/tmp/straight-stderr-2429262  /tmp/straight-stderr-2497739  /tmp/straight-stderr-2506765  /tmp/straight-stderr-2508151  /tmp/straight-stderr-2511381  /tmp/straight-stderr-2516314  /tmp/straight-stderr-2516684  /tmp/straight-stderr-2535347  /tmp/straight-stderr-2593457
```
### Version information

* Emacs version: GNU Emacs 28.1
* Operating system: Gentoo

**Comment by progfolio** [comment]
These files are created when straight runs a external process.
If the process errors, that file is used to store the error so we can relay it to the user.
It would be ideal to use a temporary buffer for this, but it's a quirk of the Emacs subprocess API that it has to be implemented like this.

That said, these are temporary files and they are created in the user's temporary directory.
Most systems will delete these on reboot. They can be deleted before hand without harming anything as well. If you're using Emacs with native compilation, you'll see that temp files are created in the same location.

Is there any functional issue you're running into with these files, or is it more that you would not like to see them in your /tmp directory?

**Comment by ajakk** [comment]
They are deleted on reboot, though I'm not sure why they're created in the first place. Surely it would be better to only create them when necessary?

**Comment by progfolio** [comment]
Let me give more context as to why these files are created.
Straight uses Emacs's `call-process` function to run programs (such as git, find, ) in a separate process. When doing so, we need to be able to distinguish the standard output of the program from the standard error stream. The signature for `call-process` allows us to specify a destination for the program's output. In order to keep track of the stderr stream separately we have to use a file:

> DESTINATION can also have the form (REAL-BUFFER STDERR-FILE); in that case,
 REAL-BUFFER says what to do with standard output, as above,
 while STDERR-FILE says what to do with standard error in the child.
 STDERR-FILE may be nil (discard standard error output),
 t (mix it with ordinary output), or a file name string.
 
Because these process calls are synchronous, we can reuse the file for all of our process calls. However, we need to account for the case where multiple Emacs instances are running simultaneously and their process errors could overwrite one another, so we append the PID of the Emacs session. This results in one file per Emacs session.

It doesn't make much sense to delete the file immediately after `straight--process-call` creates it because we're going to reuse it. There's no harm in having these temp files in your temp directory, but if you would like to get rid of them you could add something like the following to your configuration:

```emacs-lisp
(defun +straight-clean-up-temp-file ()
  "Delete current Emacs sessions's straight stderr file."
  (when (and (boundp 'straight--process-stderr)
             (file-exists-p straight--process-stderr))
    (delete-file straight--process-stderr)))

(add-hook 'kill-emacs-hook #'+straight-clean-up-temp-file)
```emacs-lisp

Does that help?

**Comment by ajakk** [comment]
It does, thanks!

**Comment by ajakk** [comment]
Though, I don't think it would be a bad idea for that to be done by straight by default.

**Comment by progfolio** [comment]
> Though, I don't think it would be a bad idea for that to be done by straight by default.

Added to the "develop" branch.

**Comment by ajakk** [comment]
Thank you!
